// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         body: {
 *             url: "https://www.example.com/"
 *         }
 *     }
 */
export interface JsonQuickActionRequest {
    /** Account ID. */
    account_id: string;
    /** Cache TTL default is 5s. Set to 0 to disable. */
    cacheTTL?: number;
    /** Rendering backend. Set to `kitesurf` to use Kitesurf (beta). */
    browser?: "kitesurf";
    body: CloudflareApi.browserRun.JsonQuickActionRequestBody;
}
