// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id"
 *     }
 */
export interface PayPerCrawlPpuZoneConfigurationUpdate {
    /** zone id */
    zone_id: string;
    enabled?: boolean;
}
