// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         zones: [{
 *                 id: "id"
 *             }]
 *     }
 */
export interface PayPerCrawlPpuZonesCanBeEnabledPayload {
    /** account id */
    account_id: string;
    zones: CloudflareApi.PayPerCrawlPpuZoneCanBeEnabledUpdate[];
}
