// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         since: "2024-01-15T09:30:00Z",
 *         until: "2024-01-15T09:30:00Z"
 *     }
 */
export interface GetAccountUsageStatsRequest {
    account_or_zone: string;
    /** account id */
    account_or_zone_id: string;
    /** Requested inclusive beginning of the statistics range as an RFC3339 timestamp. Rounded down to the selected UTC interval. */
    since: string;
    /** Requested exclusive end of the statistics range as an RFC3339 timestamp. Rounded down to the selected UTC interval. The requested duration from since cannot exceed 31 days. */
    until: string;
    /** Page number. */
    page?: number;
    /** Results per page. */
    per_page?: number;
}
