// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         body: {
 *             oauth_configuration: {},
 *             type: "end_user",
 *             user_populations: ["f174e90a-fafe-4643-bbbc-4a0ed4fc8415"]
 *         }
 *     }
 */
export interface CreateApplicationsRequest {
    account_or_zone: string;
    /** Identifier. */
    account_or_zone_id: string;
    body: CloudflareApi.AccessAppRequest;
}
