// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         match_percent: 1,
 *         name: "name"
 *     }
 */
export interface DlpNewDocumentFingerprint {
    account_id: string;
    description?: string;
    match_percent: number;
    name: string;
}
