// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "023e105f4ecef8ad9ca31a8372d0c353"
 *     }
 */
export interface BillableUsageApiV2UsageQuery {
    /** Identifies the Cloudflare account. */
    account_id: CloudflareApi.BillableUsageApiIdentifier;
    FilterBy?: CloudflareApi.BillableUsageApiV2FilterBy;
    /** Grouping definitions used to split result rows. At most two unique keys may be supplied. */
    GroupBy?: CloudflareApi.BillableUsageApiV2GroupBy[];
    /** Type of cost/usage records to retrieve. `usage` returns unrated usage quantities. Unrelated to `FilterBy.BillableMetricIds`. Defaults to `usage` when omitted. */
    Metric?: "usage";
    TimePeriod?: CloudflareApi.BillableUsageApiV2TimePeriod;
}
