// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { CustomDomainsClient } from "../resources/customDomains/client/Client.js";
import { CustomProvidersClient } from "../resources/customProviders/client/Client.js";
import { DatasetsClient } from "../resources/datasets/client/Client.js";
import { DynamicRoutingClient } from "../resources/dynamicRouting/client/Client.js";
import { EvaluationsClient } from "../resources/evaluations/client/Client.js";
import { EvaluationTypesClient } from "../resources/evaluationTypes/client/Client.js";
import { GatewaysClient } from "../resources/gateways/client/Client.js";
import { LogsClient } from "../resources/logs/client/Client.js";

export declare namespace AiGatewayClient {
    export type Options = BaseClientOptions;
}

export class AiGatewayClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AiGatewayClient.Options>;
    protected _customProviders: CustomProvidersClient | undefined;
    protected _evaluationTypes: EvaluationTypesClient | undefined;
    protected _gateways: GatewaysClient | undefined;
    protected _customDomains: CustomDomainsClient | undefined;
    protected _datasets: DatasetsClient | undefined;
    protected _evaluations: EvaluationsClient | undefined;
    protected _logs: LogsClient | undefined;
    protected _dynamicRouting: DynamicRoutingClient | undefined;

    constructor(options: AiGatewayClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get customProviders(): CustomProvidersClient {
        return (this._customProviders ??= new CustomProvidersClient(this._options));
    }

    public get evaluationTypes(): EvaluationTypesClient {
        return (this._evaluationTypes ??= new EvaluationTypesClient(this._options));
    }

    public get gateways(): GatewaysClient {
        return (this._gateways ??= new GatewaysClient(this._options));
    }

    public get customDomains(): CustomDomainsClient {
        return (this._customDomains ??= new CustomDomainsClient(this._options));
    }

    public get datasets(): DatasetsClient {
        return (this._datasets ??= new DatasetsClient(this._options));
    }

    public get evaluations(): EvaluationsClient {
        return (this._evaluations ??= new EvaluationsClient(this._options));
    }

    public get logs(): LogsClient {
        return (this._logs ??= new LogsClient(this._options));
    }

    public get dynamicRouting(): DynamicRoutingClient {
        return (this._dynamicRouting ??= new DynamicRoutingClient(this._options));
    }
}
