// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { ConfigClient } from "../resources/config/client/Client.js";
import { CrawlerClient } from "../resources/crawler/client/Client.js";
import { CrawlersClient } from "../resources/crawlers/client/Client.js";
import { PublisherClient } from "../resources/publisher/client/Client.js";
import { TermsClient } from "../resources/terms/client/Client.js";
import { ZonesClient } from "../resources/zones/client/Client.js";

export declare namespace PayPerCrawlClient {
    export type Options = BaseClientOptions;
}

export class PayPerCrawlClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PayPerCrawlClient.Options>;
    protected _crawlers: CrawlersClient | undefined;
    protected _terms: TermsClient | undefined;
    protected _zones: ZonesClient | undefined;
    protected _config: ConfigClient | undefined;
    protected _crawler: CrawlerClient | undefined;
    protected _publisher: PublisherClient | undefined;

    constructor(options: PayPerCrawlClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get crawlers(): CrawlersClient {
        return (this._crawlers ??= new CrawlersClient(this._options));
    }

    public get terms(): TermsClient {
        return (this._terms ??= new TermsClient(this._options));
    }

    public get zones(): ZonesClient {
        return (this._zones ??= new ZonesClient(this._options));
    }

    public get config(): ConfigClient {
        return (this._config ??= new ConfigClient(this._options));
    }

    public get crawler(): CrawlerClient {
        return (this._crawler ??= new CrawlerClient(this._options));
    }

    public get publisher(): PublisherClient {
        return (this._publisher ??= new PublisherClient(this._options));
    }
}
