// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         article_id: "article_id",
 *         skill_id: "skill_id",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface RunSkillsRequest {
    account_id: string;
    article_id: string;
    skill_id: string;
    body: Record<string, unknown>;
}
