// This file was auto-generated by Fern from our API Definition.

export interface WebsearchAiResponse {
    items: WebsearchAiResponse.Items.Item[];
    metadata: WebsearchAiResponse.Metadata;
}

export namespace WebsearchAiResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            description?: string | undefined;
            faviconUrl?: string | undefined;
            imageUrl?: string | undefined;
            lastModifiedDate?: string | undefined;
            title: string;
            url: string;
        }
    }

    export interface Metadata {
        latencyMs: number;
        query: string;
        requestId: string;
    }
}
