// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         "node-id": "tunnel_id",
 *         connector_id: "connector_id"
 *     }
 */
export interface GetConnectorsRequest {
    /** Cloudflare account ID */
    account_id: string;
    /** UUID of the tunnel. */
    "node-id": string;
    /** UUID of the Cloudflare Tunnel connector. */
    connector_id: string;
}
