// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "a86a8f5c339544d7bdc89926de14fb8c",
 *         id: "my-mcp-server"
 *     }
 */
export interface UpdateServersRequest {
    account_id: string;
    /** Unique identifier for the MCP server. */
    id: string;
    /** Credential configuration for the upstream MCP server. For auth_type "bearer", either a raw token string (e.g. "sk-abc123"), which is wrapped server-side as `Authorization: Bearer <token>`, or a JSON-encoded object of the form `{"headers":{"Header-Name":"value",...}}` for custom or multiple static headers (e.g. Cloudflare Access service tokens: `{"headers":{"cf-access-client-id":"...","cf-access-client-secret":"..."}}`). For auth_type "oauth" with a pre-registered client, send a JSON-encoded object containing `auth_mode:"manual"`, `config.authorization_endpoint`, `config.token_endpoint`, and `registration_info.client_id`. Also provide `registration_info.redirect_uris` unless `is_shared_oauth_callback_enabled` is true. Optional fields include `config.issuer`, `config.revocation_endpoint`, `registration_info.scope`, and `registration_info.token_endpoint_auth_method`. Send the client secret in the separate `client_secret` field. Omit `auth_credentials` on update to preserve the existing configuration. */
    auth_credentials?: string;
    /** Pre-registered OAuth client_secret. Write-only - accepted on create/update when auth_credentials.auth_mode is 'manual'. Required when creating a manual OAuth server or converting an existing server to manual mode. Omit it on update to preserve the existing secret; provide it to rotate the secret. Stored AES-GCM-encrypted in server_oauth_secrets; never returned by read endpoints. */
    client_secret?: string;
    /** Optional description of the MCP server. */
    description?: string | null;
    /** When true, the gateway worker uses the shared Cloudflare-owned OAuth callback endpoint as the redirect_uri for upstream on-behalf OAuth, instead of the customer portal hostname. Defaults to false (off); opt in per server by setting true. */
    is_shared_oauth_callback_enabled?: boolean;
    /** Display name for the MCP server. */
    name?: string;
    /** Route outbound traffic to this MCP server through Zero Trust Secure Web Gateway. */
    secure_web_gateway?: boolean;
    /** Server-wide prompt capability overrides. */
    updated_prompts?: UpdateServersRequest.UpdatedPrompts.Item[];
    /** Server-wide tool capability overrides. */
    updated_tools?: UpdateServersRequest.UpdatedTools.Item[];
}

export namespace UpdateServersRequest {
    export type UpdatedPrompts = UpdatedPrompts.Item[];

    export namespace UpdatedPrompts {
        export interface Item {
            /** Custom name exposed for the capability. */
            alias?: string | undefined;
            /** Custom description exposed for the capability. */
            description?: string | undefined;
            /** Whether the capability is available through the MCP server. */
            enabled?: boolean | undefined;
            /** Name of the tool or prompt capability to override. */
            name: string;
        }
    }

    export type UpdatedTools = UpdatedTools.Item[];

    export namespace UpdatedTools {
        export interface Item {
            /** Custom name exposed for the capability. */
            alias?: string | undefined;
            /** Custom description exposed for the capability. */
            description?: string | undefined;
            /** Whether the capability is available through the MCP server. */
            enabled?: boolean | undefined;
            /** Name of the tool or prompt capability to override. */
            name: string;
        }
    }
}
