// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "023e105f4ecef8ad9ca31a8372d0c353",
 *         user_population_id: "f174e90a-fafe-4643-bbbc-4a0ed4fc8415"
 *     }
 */
export interface DeleteUserPopulationsRequest {
    account_id: CloudflareApi.AccessIdentifier;
    user_population_id: CloudflareApi.AccessUuid;
}
