// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "023e105f4ecef8ad9ca31a8372d0c353"
 *     }
 */
export interface ListUserPopulationsRequest {
    account_id: CloudflareApi.AccessIdentifier;
    /** Page number of results. */
    page?: number;
    /** Number of results per page. */
    per_page?: number;
}
