// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface GetConfigurationOperatorRequest {
    /** account id */
    account_id: string;
}
