// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface PayPerCrawlPpuOperatorConfigurationUpdate {
    /** account id */
    account_id: string;
    /** Default price in microcents. 1 USD = 100,000,000 microcents. Must be a multiple of 100,000 ($0.001) between $0.001 and $9,999.999. */
    default_price_usd_microcents?: number;
    enabled?: boolean;
    name?: string;
}
