// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         body: {
 *             default_price_usd_microcents: 1,
 *             enabled: true,
 *             name: "name"
 *         }
 *     }
 */
export interface SetConfigurationOperatorRequest {
    /** account id */
    account_id: string;
    body: CloudflareApi.PayPerCrawlPpuOperatorConfiguration;
}
