// This file was auto-generated by Fern from our API Definition.

export interface AbuseReportsAppealEligibility {
    /** Number of appeals submitted against the report so far. */
    appeal_count: number;
    /** Whether the report can currently be appealed under the policy applied to it. */
    appealable: boolean;
    /** Whether the report has at least one mitigation an appeal could reverse. */
    has_appealable_mitigations: boolean;
    /** Whether the report already has an open (undecided) appeal. */
    has_open_appeal: boolean;
    /** Maximum number of appeals allowed per report. */
    max_appeals: number;
}
