// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessPingone {
    config: AccessPingone.Config;
    id?: CloudflareApi.AccessUuid | undefined;
    name: CloudflareApi.AccessName3;
    /** Indicates that the identity provider is immutable and cannot be updated or deleted via the API. */
    read_only?: boolean | undefined;
    /**
     * The SAML encryption certificate set details, including current and previous certificates.
     * Only present for SAML identity providers with a certificate set assigned.
     */
    saml_certificate_set?: CloudflareApi.AccessSamlCertificateSet | undefined;
    /**
     * The UID of the SAML encryption certificate set assigned to this Identity Provider.
     * Only present for SAML identity providers with encryption configured.
     * Create a certificate set via POST to `/identity_providers/{id}/saml_certificate`.
     */
    saml_certificate_set_id?: string | undefined;
    scim_config?: CloudflareApi.AccessIdentityProviderScimConfig | undefined;
    /** The type of identity provider. To determine the value for a specific provider, refer to our [developer documentation](https://developers.cloudflare.com/cloudflare-one/identity/idp-integration/). */
    type: AccessPingone.Type;
}

export namespace AccessPingone {
    export interface Config extends CloudflareApi.AccessGenericOauthConfig, CloudflareApi.AccessCustomClaimsSupport {
        /** Your PingOne environment identifier */
        ping_env_id?: string | undefined;
    }

    /** The type of identity provider. To determine the value for a specific provider, refer to our [developer documentation](https://developers.cloudflare.com/cloudflare-one/identity/idp-integration/). */
    export const Type = {
        Onetimepin: "onetimepin",
        AzureAd: "azureAD",
        Saml: "saml",
        Centrify: "centrify",
        Facebook: "facebook",
        Github: "github",
        GoogleApps: "google-apps",
        Google: "google",
        Linkedin: "linkedin",
        Oidc: "oidc",
        Okta: "okta",
        Onelogin: "onelogin",
        Pingone: "pingone",
        Yandex: "yandex",
        Cloudflare: "cloudflare",
        Passkeys: "passkeys",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
