// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessResponseCollection18 {
    errors: CloudflareApi.AccessMessages;
    messages: CloudflareApi.AccessMessages;
    /** Whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.AccessResponseCollection18ResultInfo | undefined;
    result?: AccessResponseCollection18.Result.Item[] | undefined;
}

export namespace AccessResponseCollection18 {
    export type Result = Result.Item[];

    export namespace Result {
        export type Item =
            | CloudflareApi.AccessAzureAd2
            | CloudflareApi.AccessCentrify2
            | CloudflareApi.AccessFacebook2
            | CloudflareApi.AccessGithub2
            | CloudflareApi.AccessGoogle2
            | CloudflareApi.AccessGoogleApps2
            | CloudflareApi.AccessLinkedin2
            | CloudflareApi.AccessOidc2
            | CloudflareApi.AccessOkta2
            | CloudflareApi.AccessOnelogin2
            | CloudflareApi.AccessPingone2
            | CloudflareApi.AccessSaml2
            | CloudflareApi.AccessYandex2
            | CloudflareApi.AccessOnetimepin2
            | CloudflareApi.AccessCloudflare2;
    }
}
