// This file was auto-generated by Fern from our API Definition.

export interface AccessPasskeysConfig {
    /** When enabled, the Access login page automatically prompts the user to authenticate with a passkey. */
    login_page_auto_prompt?: boolean | undefined;
    redirect_url?: string | undefined;
}
