// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessMcpPortalProps {
    allow_authenticate_via_warp?: CloudflareApi.AccessAllowAuthenticateViaWarp2 | undefined;
    allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
    auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
    custom_deny_message?: CloudflareApi.AccessCustomDenyMessage | undefined;
    custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
    custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
    custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
    destinations?: CloudflareApi.AccessDestinations | undefined;
    domain?: CloudflareApi.AccessDomain | undefined;
    http_only_cookie_attribute?: CloudflareApi.AccessHttpOnlyCookieAttribute | undefined;
    logo_url?: CloudflareApi.AccessLogoUrl | undefined;
    name?: CloudflareApi.AccessName8 | undefined;
    oauth_configuration?: CloudflareApi.AccessOauthConfiguration | undefined;
    options_preflight_bypass?: CloudflareApi.AccessOptionsPreflightBypass | undefined;
    same_site_cookie_attribute?: CloudflareApi.AccessSameSiteCookieAttribute | undefined;
    scim_config?: CloudflareApi.AccessScimConfig | undefined;
    session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
    tags?: CloudflareApi.AccessTags | undefined;
    /** The application type. */
    type: AccessMcpPortalProps.Type;
}

export namespace AccessMcpPortalProps {
    /** The application type. */
    export const Type = {
        SelfHosted: "self_hosted",
        EndUser: "end_user",
        Saas: "saas",
        Ssh: "ssh",
        Vnc: "vnc",
        AppLauncher: "app_launcher",
        Warp: "warp",
        Biso: "biso",
        Bookmark: "bookmark",
        DashSso: "dash_sso",
        Infrastructure: "infrastructure",
        Rdp: "rdp",
        Mcp: "mcp",
        McpPortal: "mcp_portal",
        ProxyEndpoint: "proxy_endpoint",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
