// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessEndUserAllWorkersDestination {
    overrides?: CloudflareApi.AccessDestinationOverrides | undefined;
}
