// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessUserPopulation {
    created_at: CloudflareApi.AccessCreatedAt;
    id: CloudflareApi.AccessUuid;
    name: CloudflareApi.AccessUserPopulationName;
    updated_at: CloudflareApi.AccessUpdatedAt;
}
