// This file was auto-generated by Fern from our API Definition.

/** The application type. */
export const AccessType = {
    SelfHosted: "self_hosted",
    EndUser: "end_user",
    Saas: "saas",
    Ssh: "ssh",
    Vnc: "vnc",
    AppLauncher: "app_launcher",
    Warp: "warp",
    Biso: "biso",
    Bookmark: "bookmark",
    DashSso: "dash_sso",
    Infrastructure: "infrastructure",
    Rdp: "rdp",
    Mcp: "mcp",
    McpPortal: "mcp_portal",
    ProxyEndpoint: "proxy_endpoint",
} as const;
export type AccessType = (typeof AccessType)[keyof typeof AccessType];
