// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessPasskeys {
    config: CloudflareApi.AccessPasskeysConfig;
    id?: CloudflareApi.AccessUuid | undefined;
    name: CloudflareApi.AccessName3;
    /** Indicates that the identity provider is immutable and cannot be updated or deleted via the API. */
    read_only?: boolean | undefined;
    /**
     * The SAML encryption certificate set details, including current and previous certificates.
     * Only present for SAML identity providers with a certificate set assigned.
     */
    saml_certificate_set?: CloudflareApi.AccessSamlCertificateSet | undefined;
    /**
     * The UID of the SAML encryption certificate set assigned to this Identity Provider.
     * Only present for SAML identity providers with encryption configured.
     * Create a certificate set via POST to `/identity_providers/{id}/saml_certificate`.
     */
    saml_certificate_set_id?: string | undefined;
    scim_config?: CloudflareApi.AccessIdentityProviderScimConfig | undefined;
    type: "passkeys";
}
