// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Public hostname and Workers destinations secured by Access.
 */
export type AccessEndUserDestinations = CloudflareApi.AccessEndUserDestinationsItem[];
