// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export type AccessIdentityProviders =
    | CloudflareApi.AccessAzureAd
    | CloudflareApi.AccessCentrify
    | CloudflareApi.AccessFacebook
    | CloudflareApi.AccessGithub
    | CloudflareApi.AccessGoogle
    | CloudflareApi.AccessGoogleApps
    | CloudflareApi.AccessLinkedin
    | CloudflareApi.AccessOidc
    | CloudflareApi.AccessOkta
    | CloudflareApi.AccessOnelogin
    | CloudflareApi.AccessPingone
    | CloudflareApi.AccessSaml
    | CloudflareApi.AccessYandex
    | CloudflareApi.AccessOnetimepin
    | CloudflareApi.AccessCloudflare
    | CloudflareApi.AccessPasskeys;
