// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessResponseCollection25 {
    result_info?: AccessResponseCollection25.ResultInfo | undefined;
    result?: CloudflareApi.AccessUsers2[] | undefined;
    errors: CloudflareApi.AccessMessages;
    messages: CloudflareApi.AccessMessages;
    /** Whether the API call was successful. */
    success: true;
}

export namespace AccessResponseCollection25 {
    export interface ResultInfo {
        count?: number | undefined;
        page?: number | undefined;
        per_page?: number | undefined;
        total_count?: number | undefined;
    }
}
