// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessProxyEndpointProps {
    allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
    auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
    custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
    custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
    custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
    /** The proxy endpoint domain in the format: 10 alphanumeric characters followed by .proxy.cloudflare-gateway.com */
    domain?: string | undefined;
    name?: string | undefined;
    session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
    /** The application type. */
    type: AccessProxyEndpointProps.Type;
}

export namespace AccessProxyEndpointProps {
    /** The application type. */
    export const Type = {
        SelfHosted: "self_hosted",
        EndUser: "end_user",
        Saas: "saas",
        Ssh: "ssh",
        Vnc: "vnc",
        AppLauncher: "app_launcher",
        Warp: "warp",
        Biso: "biso",
        Bookmark: "bookmark",
        DashSso: "dash_sso",
        Infrastructure: "infrastructure",
        Rdp: "rdp",
        Mcp: "mcp",
        McpPortal: "mcp_portal",
        ProxyEndpoint: "proxy_endpoint",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
