// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessSaasProps {
    allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
    app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
    auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
    custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
    logo_url?: CloudflareApi.AccessLogoUrl | undefined;
    name?: CloudflareApi.AccessName8 | undefined;
    saas_app?: AccessSaasProps.SaasApp | undefined;
    scim_config?: CloudflareApi.AccessScimConfig | undefined;
    tags?: CloudflareApi.AccessTags | undefined;
    /** The application type. */
    type?: AccessSaasProps.Type | undefined;
}

export namespace AccessSaasProps {
    export type SaasApp = CloudflareApi.AccessSamlSaasApp | CloudflareApi.AccessOidcSaasApp;
    /** The application type. */
    export const Type = {
        SelfHosted: "self_hosted",
        EndUser: "end_user",
        Saas: "saas",
        Ssh: "ssh",
        Vnc: "vnc",
        AppLauncher: "app_launcher",
        Warp: "warp",
        Biso: "biso",
        Bookmark: "bookmark",
        DashSso: "dash_sso",
        Infrastructure: "infrastructure",
        Rdp: "rdp",
        Mcp: "mcp",
        McpPortal: "mcp_portal",
        ProxyEndpoint: "proxy_endpoint",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
