// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessResponseCollection {
    errors: CloudflareApi.AccessMessages;
    messages: CloudflareApi.AccessMessages;
    /** Whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.AccessResponseCollectionResultInfo | undefined;
    result?: AccessResponseCollection.Result.Item[] | undefined;
}

export namespace AccessResponseCollection {
    export type Result = Result.Item[];

    export namespace Result {
        export type Item =
            | CloudflareApi.AccessAzureAd
            | CloudflareApi.AccessCentrify
            | CloudflareApi.AccessFacebook
            | CloudflareApi.AccessGithub
            | CloudflareApi.AccessGoogle
            | CloudflareApi.AccessGoogleApps
            | CloudflareApi.AccessLinkedin
            | CloudflareApi.AccessOidc
            | CloudflareApi.AccessOkta
            | CloudflareApi.AccessOnelogin
            | CloudflareApi.AccessPingone
            | CloudflareApi.AccessSaml
            | CloudflareApi.AccessYandex
            | CloudflareApi.AccessOnetimepin
            | CloudflareApi.AccessCloudflare
            | CloudflareApi.AccessPasskeys;
    }
}
