// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessBookmarkProps {
    app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
    /** The URL or domain of the bookmark. */
    domain?: string | undefined;
    logo_url?: CloudflareApi.AccessLogoUrl | undefined;
    name?: CloudflareApi.AccessName8 | undefined;
    tags?: CloudflareApi.AccessTags | undefined;
    /** The application type. */
    type?: AccessBookmarkProps.Type | undefined;
}

export namespace AccessBookmarkProps {
    /** The application type. */
    export const Type = {
        SelfHosted: "self_hosted",
        EndUser: "end_user",
        Saas: "saas",
        Ssh: "ssh",
        Vnc: "vnc",
        AppLauncher: "app_launcher",
        Warp: "warp",
        Biso: "biso",
        Bookmark: "bookmark",
        DashSso: "dash_sso",
        Infrastructure: "infrastructure",
        Rdp: "rdp",
        Mcp: "mcp",
        McpPortal: "mcp_portal",
        ProxyEndpoint: "proxy_endpoint",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
