// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessResponseCollection11 {
    errors: CloudflareApi.AccessMessages;
    messages: CloudflareApi.AccessMessages;
    /** Whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.AccessResponseCollection11ResultInfo | undefined;
    result?: CloudflareApi.AccessCustomPageWithoutHtml[] | undefined;
}
