// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessEndUserWorkerDestination {
    overrides?: CloudflareApi.AccessDestinationOverrides | undefined;
    /** The ID of the Cloudflare Worker to secure. */
    worker_id: string;
}
