// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * **Beta:** Optional configuration for managing an OAuth authorization flow controlled by Access. When set, Access will act as the OAuth authorization server for this application. Only compatible with OAuth clients that support [RFC 8707](https://datatracker.ietf.org/doc/html/rfc8707) (Resource Indicators for OAuth 2.0). This feature is currently in beta.
 */
export interface AccessEndUserOauthConfiguration {
    dynamic_client_registration?: CloudflareApi.AccessOauthConfigurationDynamicClientRegistration | undefined;
    /** Managed OAuth is required for end user applications and cannot be disabled. */
    enabled?: true | undefined;
    grant?: CloudflareApi.AccessOauthConfigurationGrant | undefined;
}
