// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessInfraProps extends CloudflareApi.AccessAppRespEmbeddedTargetCriteriaInfra {
    mfa_config?: CloudflareApi.AccessInfraMfaConfig | undefined;
    name?: CloudflareApi.AccessName8 | undefined;
    /** The application type. */
    type: AccessInfraProps.Type;
}

export namespace AccessInfraProps {
    /** The application type. */
    export const Type = {
        SelfHosted: "self_hosted",
        EndUser: "end_user",
        Saas: "saas",
        Ssh: "ssh",
        Vnc: "vnc",
        AppLauncher: "app_launcher",
        Warp: "warp",
        Biso: "biso",
        Bookmark: "bookmark",
        DashSso: "dash_sso",
        Infrastructure: "infrastructure",
        Rdp: "rdp",
        Mcp: "mcp",
        McpPortal: "mcp_portal",
        ProxyEndpoint: "proxy_endpoint",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
