// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export type AccessAppResponse =
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          destinations?: CloudflareApi.AccessEndUserDestinations | undefined;
          domain?: CloudflareApi.AccessDomain | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          oauth_configuration: CloudflareApi.AccessEndUserOauthConfiguration;
          self_hosted_domains?: CloudflareApi.AccessSelfHostedDomains | undefined;
          type: "end_user";
          user_populations: CloudflareApi.AccessUuid[];
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allow_authenticate_via_warp?: CloudflareApi.AccessAllowAuthenticateViaWarp2 | undefined;
          allow_iframe?: CloudflareApi.AccessAllowIframe | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          cors_headers?: CloudflareApi.AccessCorsHeaders | undefined;
          custom_deny_message?: CloudflareApi.AccessCustomDenyMessage | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          destinations?: CloudflareApi.AccessDestinations | undefined;
          domain: CloudflareApi.AccessDomain;
          eager_redirect_cookie_setting?: CloudflareApi.AccessEagerRedirectCookieSetting | undefined;
          enable_binding_cookie?: CloudflareApi.AccessEnableBindingCookie | undefined;
          http_only_cookie_attribute?: CloudflareApi.AccessHttpOnlyCookieAttribute | undefined;
          logo_url?: CloudflareApi.AccessLogoUrl | undefined;
          mfa_config?: CloudflareApi.AccessMfaConfig | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          oauth_configuration?: CloudflareApi.AccessOauthConfiguration | undefined;
          options_preflight_bypass?: CloudflareApi.AccessOptionsPreflightBypass | undefined;
          path_cookie_attribute?: CloudflareApi.AccessPathCookieAttribute | undefined;
          read_service_tokens_from_header?: CloudflareApi.AccessReadServiceTokensFromHeader | undefined;
          same_site_cookie_attribute?: CloudflareApi.AccessSameSiteCookieAttribute | undefined;
          scim_config?: CloudflareApi.AccessScimConfig | undefined;
          self_hosted_domains?: CloudflareApi.AccessSelfHostedDomains | undefined;
          service_auth_401_redirect?: CloudflareApi.AccessServiceAuth401Redirect | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          skip_interstitial?: CloudflareApi.AccessSkipInterstitial | undefined;
          tags?: CloudflareApi.AccessTags | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          use_clientless_isolation_app_launcher_url?:
              | CloudflareApi.AccessUseClientlessIsolationAppLauncherUrl
              | undefined;
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          logo_url?: CloudflareApi.AccessLogoUrl | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          saas_app?: (CloudflareApi.AccessSamlSaasApp | CloudflareApi.AccessOidcSaasApp) | undefined;
          scim_config?: CloudflareApi.AccessScimConfig | undefined;
          tags?: CloudflareApi.AccessTags | undefined;
          type?:
              | (
                    | "self_hosted"
                    | "end_user"
                    | "saas"
                    | "ssh"
                    | "vnc"
                    | "app_launcher"
                    | "warp"
                    | "biso"
                    | "bookmark"
                    | "dash_sso"
                    | "infrastructure"
                    | "rdp"
                    | "mcp"
                    | "mcp_portal"
                    | "proxy_endpoint"
                )
              | undefined;
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allow_authenticate_via_warp?: CloudflareApi.AccessAllowAuthenticateViaWarp2 | undefined;
          allow_iframe?: CloudflareApi.AccessAllowIframe | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          cors_headers?: CloudflareApi.AccessCorsHeaders | undefined;
          custom_deny_message?: CloudflareApi.AccessCustomDenyMessage | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          destinations?: CloudflareApi.AccessDestinations | undefined;
          domain: CloudflareApi.AccessDomain;
          eager_redirect_cookie_setting?: CloudflareApi.AccessEagerRedirectCookieSetting | undefined;
          enable_binding_cookie?: CloudflareApi.AccessEnableBindingCookie | undefined;
          http_only_cookie_attribute?: CloudflareApi.AccessHttpOnlyCookieAttribute | undefined;
          logo_url?: CloudflareApi.AccessLogoUrl | undefined;
          mfa_config?: CloudflareApi.AccessMfaConfig | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          oauth_configuration?: CloudflareApi.AccessOauthConfiguration | undefined;
          options_preflight_bypass?: CloudflareApi.AccessOptionsPreflightBypass | undefined;
          path_cookie_attribute?: CloudflareApi.AccessPathCookieAttribute | undefined;
          read_service_tokens_from_header?: CloudflareApi.AccessReadServiceTokensFromHeader | undefined;
          same_site_cookie_attribute?: CloudflareApi.AccessSameSiteCookieAttribute | undefined;
          scim_config?: CloudflareApi.AccessScimConfig | undefined;
          self_hosted_domains?: CloudflareApi.AccessSelfHostedDomains | undefined;
          service_auth_401_redirect?: CloudflareApi.AccessServiceAuth401Redirect | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          skip_interstitial?: CloudflareApi.AccessSkipInterstitial | undefined;
          tags?: CloudflareApi.AccessTags | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          use_clientless_isolation_app_launcher_url?:
              | CloudflareApi.AccessUseClientlessIsolationAppLauncherUrl
              | undefined;
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allow_authenticate_via_warp?: CloudflareApi.AccessAllowAuthenticateViaWarp2 | undefined;
          allow_iframe?: CloudflareApi.AccessAllowIframe | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          cors_headers?: CloudflareApi.AccessCorsHeaders | undefined;
          custom_deny_message?: CloudflareApi.AccessCustomDenyMessage | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          destinations?: CloudflareApi.AccessDestinations | undefined;
          domain: CloudflareApi.AccessDomain;
          eager_redirect_cookie_setting?: CloudflareApi.AccessEagerRedirectCookieSetting | undefined;
          enable_binding_cookie?: CloudflareApi.AccessEnableBindingCookie | undefined;
          http_only_cookie_attribute?: CloudflareApi.AccessHttpOnlyCookieAttribute | undefined;
          logo_url?: CloudflareApi.AccessLogoUrl | undefined;
          mfa_config?: CloudflareApi.AccessMfaConfig | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          oauth_configuration?: CloudflareApi.AccessOauthConfiguration | undefined;
          options_preflight_bypass?: CloudflareApi.AccessOptionsPreflightBypass | undefined;
          path_cookie_attribute?: CloudflareApi.AccessPathCookieAttribute | undefined;
          read_service_tokens_from_header?: CloudflareApi.AccessReadServiceTokensFromHeader | undefined;
          same_site_cookie_attribute?: CloudflareApi.AccessSameSiteCookieAttribute | undefined;
          scim_config?: CloudflareApi.AccessScimConfig | undefined;
          self_hosted_domains?: CloudflareApi.AccessSelfHostedDomains | undefined;
          service_auth_401_redirect?: CloudflareApi.AccessServiceAuth401Redirect | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          skip_interstitial?: CloudflareApi.AccessSkipInterstitial | undefined;
          tags?: CloudflareApi.AccessTags | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          use_clientless_isolation_app_launcher_url?:
              | CloudflareApi.AccessUseClientlessIsolationAppLauncherUrl
              | undefined;
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          domain?: string | undefined;
          name?: string | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          app_launcher_logo_url?: CloudflareApi.AccessAppLauncherLogoUrl | undefined;
          bg_color?: CloudflareApi.AccessBgColor | undefined;
          footer_links?: CloudflareApi.AccessFooterLinks | undefined;
          header_bg_color?: CloudflareApi.AccessHeaderBgColor | undefined;
          landing_page_design?: CloudflareApi.AccessLandingPageDesign | undefined;
          skip_app_launcher_login_page?: CloudflareApi.AccessSkipAppLauncherLoginPage | undefined;
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          domain?: string | undefined;
          name?: string | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          domain?: string | undefined;
          name?: string | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          domain?: string | undefined;
          name?: string | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
          domain?: string | undefined;
          logo_url?: CloudflareApi.AccessLogoUrl | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          tags?: CloudflareApi.AccessTags | undefined;
          type?:
              | (
                    | "self_hosted"
                    | "end_user"
                    | "saas"
                    | "ssh"
                    | "vnc"
                    | "app_launcher"
                    | "warp"
                    | "biso"
                    | "bookmark"
                    | "dash_sso"
                    | "infrastructure"
                    | "rdp"
                    | "mcp"
                    | "mcp_portal"
                    | "proxy_endpoint"
                )
              | undefined;
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          mfa_config?: CloudflareApi.AccessInfraMfaConfig | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          target_criteria: CloudflareApi.AccessTargetCriteriaInfraApp[];
          policies?: CloudflareApi.AccessInfraPolicyResp[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          target_criteria: CloudflareApi.AccessTargetCriteriaSelfHostedApp[];
          allow_authenticate_via_warp?: CloudflareApi.AccessAllowAuthenticateViaWarp2 | undefined;
          allow_iframe?: CloudflareApi.AccessAllowIframe | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          cors_headers?: CloudflareApi.AccessCorsHeaders | undefined;
          custom_deny_message?: CloudflareApi.AccessCustomDenyMessage | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          destinations?: CloudflareApi.AccessDestinations | undefined;
          domain: CloudflareApi.AccessDomain;
          eager_redirect_cookie_setting?: CloudflareApi.AccessEagerRedirectCookieSetting | undefined;
          enable_binding_cookie?: CloudflareApi.AccessEnableBindingCookie | undefined;
          http_only_cookie_attribute?: CloudflareApi.AccessHttpOnlyCookieAttribute | undefined;
          logo_url?: CloudflareApi.AccessLogoUrl | undefined;
          mfa_config?: CloudflareApi.AccessMfaConfig | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          oauth_configuration?: CloudflareApi.AccessOauthConfiguration | undefined;
          options_preflight_bypass?: CloudflareApi.AccessOptionsPreflightBypass | undefined;
          path_cookie_attribute?: CloudflareApi.AccessPathCookieAttribute | undefined;
          read_service_tokens_from_header?: CloudflareApi.AccessReadServiceTokensFromHeader | undefined;
          same_site_cookie_attribute?: CloudflareApi.AccessSameSiteCookieAttribute | undefined;
          scim_config?: CloudflareApi.AccessScimConfig | undefined;
          self_hosted_domains?: CloudflareApi.AccessSelfHostedDomains | undefined;
          service_auth_401_redirect?: CloudflareApi.AccessServiceAuth401Redirect | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          skip_interstitial?: CloudflareApi.AccessSkipInterstitial | undefined;
          tags?: CloudflareApi.AccessTags | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          use_clientless_isolation_app_launcher_url?:
              | CloudflareApi.AccessUseClientlessIsolationAppLauncherUrl
              | undefined;
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allow_authenticate_via_warp?: CloudflareApi.AccessAllowAuthenticateViaWarp2 | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          custom_deny_message?: CloudflareApi.AccessCustomDenyMessage | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          destinations?: CloudflareApi.AccessDestinations | undefined;
          http_only_cookie_attribute?: CloudflareApi.AccessHttpOnlyCookieAttribute | undefined;
          logo_url?: CloudflareApi.AccessLogoUrl | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          oauth_configuration?: CloudflareApi.AccessOauthConfiguration | undefined;
          options_preflight_bypass?: CloudflareApi.AccessOptionsPreflightBypass | undefined;
          same_site_cookie_attribute?: CloudflareApi.AccessSameSiteCookieAttribute | undefined;
          scim_config?: CloudflareApi.AccessScimConfig | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          tags?: CloudflareApi.AccessTags | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      }
    | {
          aud?: CloudflareApi.AccessAud2 | undefined;
          created_at?: CloudflareApi.AccessCreatedAt | undefined;
          id?: CloudflareApi.AccessUuid | undefined;
          updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
          allow_authenticate_via_warp?: CloudflareApi.AccessAllowAuthenticateViaWarp2 | undefined;
          allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
          auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
          custom_deny_message?: CloudflareApi.AccessCustomDenyMessage | undefined;
          custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
          custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
          custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
          destinations?: CloudflareApi.AccessDestinations | undefined;
          domain?: CloudflareApi.AccessDomain | undefined;
          http_only_cookie_attribute?: CloudflareApi.AccessHttpOnlyCookieAttribute | undefined;
          logo_url?: CloudflareApi.AccessLogoUrl | undefined;
          name?: CloudflareApi.AccessName8 | undefined;
          oauth_configuration?: CloudflareApi.AccessOauthConfiguration | undefined;
          options_preflight_bypass?: CloudflareApi.AccessOptionsPreflightBypass | undefined;
          same_site_cookie_attribute?: CloudflareApi.AccessSameSiteCookieAttribute | undefined;
          scim_config?: CloudflareApi.AccessScimConfig | undefined;
          session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
          tags?: CloudflareApi.AccessTags | undefined;
          type:
              | "self_hosted"
              | "end_user"
              | "saas"
              | "ssh"
              | "vnc"
              | "app_launcher"
              | "warp"
              | "biso"
              | "bookmark"
              | "dash_sso"
              | "infrastructure"
              | "rdp"
              | "mcp"
              | "mcp_portal"
              | "proxy_endpoint";
          policies?: CloudflareApi.AccessAppPolicyResponse[] | undefined;
      };
