// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * An end user application is a public self-hosted application backed by exactly one organization-owned user population. End user applications use a canonical allow-everyone policy and do not support custom policies, SCIM configuration, MFA configuration, or private destinations.
 */
export interface AccessEndUserProps {
    allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
    destinations?: CloudflareApi.AccessEndUserDestinations | undefined;
    domain?: CloudflareApi.AccessDomain | undefined;
    name?: CloudflareApi.AccessName8 | undefined;
    oauth_configuration: CloudflareApi.AccessEndUserOauthConfiguration;
    self_hosted_domains?: CloudflareApi.AccessSelfHostedDomains | undefined;
    /** The application type. */
    type: "end_user";
    /** The single user population associated with this application. */
    user_populations: CloudflareApi.AccessUuid[];
}
