// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessVncProps {
    allow_authenticate_via_warp?: CloudflareApi.AccessAllowAuthenticateViaWarp2 | undefined;
    allow_iframe?: CloudflareApi.AccessAllowIframe | undefined;
    allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
    app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
    auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
    cors_headers?: CloudflareApi.AccessCorsHeaders | undefined;
    custom_deny_message?: CloudflareApi.AccessCustomDenyMessage | undefined;
    custom_deny_url?: CloudflareApi.AccessCustomDenyUrl | undefined;
    custom_non_identity_deny_url?: CloudflareApi.AccessCustomNonIdentityDenyUrl | undefined;
    custom_pages?: CloudflareApi.AccessCustomPages2 | undefined;
    destinations?: CloudflareApi.AccessDestinations | undefined;
    domain: CloudflareApi.AccessDomain;
    eager_redirect_cookie_setting?: CloudflareApi.AccessEagerRedirectCookieSetting | undefined;
    enable_binding_cookie?: CloudflareApi.AccessEnableBindingCookie | undefined;
    http_only_cookie_attribute?: CloudflareApi.AccessHttpOnlyCookieAttribute | undefined;
    logo_url?: CloudflareApi.AccessLogoUrl | undefined;
    mfa_config?: CloudflareApi.AccessMfaConfig | undefined;
    name?: CloudflareApi.AccessName8 | undefined;
    oauth_configuration?: CloudflareApi.AccessOauthConfiguration | undefined;
    options_preflight_bypass?: CloudflareApi.AccessOptionsPreflightBypass | undefined;
    path_cookie_attribute?: CloudflareApi.AccessPathCookieAttribute | undefined;
    read_service_tokens_from_header?: CloudflareApi.AccessReadServiceTokensFromHeader | undefined;
    same_site_cookie_attribute?: CloudflareApi.AccessSameSiteCookieAttribute | undefined;
    scim_config?: CloudflareApi.AccessScimConfig | undefined;
    self_hosted_domains?: CloudflareApi.AccessSelfHostedDomains | undefined;
    service_auth_401_redirect?: CloudflareApi.AccessServiceAuth401Redirect | undefined;
    session_duration?: CloudflareApi.AccessSessionDuration2 | undefined;
    skip_interstitial?: CloudflareApi.AccessSkipInterstitial | undefined;
    tags?: CloudflareApi.AccessTags | undefined;
    /** The application type. */
    type: AccessVncProps.Type;
    use_clientless_isolation_app_launcher_url?: CloudflareApi.AccessUseClientlessIsolationAppLauncherUrl | undefined;
}

export namespace AccessVncProps {
    /** The application type. */
    export const Type = {
        SelfHosted: "self_hosted",
        EndUser: "end_user",
        Saas: "saas",
        Ssh: "ssh",
        Vnc: "vnc",
        AppLauncher: "app_launcher",
        Warp: "warp",
        Biso: "biso",
        Bookmark: "bookmark",
        DashSso: "dash_sso",
        Infrastructure: "infrastructure",
        Rdp: "rdp",
        Mcp: "mcp",
        McpPortal: "mcp_portal",
        ProxyEndpoint: "proxy_endpoint",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
