// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessEndUserPreviewWorkerDestination {
    overrides?: CloudflareApi.AccessDestinationOverrides | undefined;
    /** The ID of the Cloudflare Worker whose previews to secure. */
    worker_id: string;
}
