// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessEndUserPublicDestination {
    overrides?: CloudflareApi.AccessDestinationOverrides | undefined;
    /** The public hostname and optional path to secure. */
    uri: string;
}
