// This file was auto-generated by Fern from our API Definition.

/**
 * The name of the user population. Leading and trailing whitespace is trimmed before validation. After trimming, the name must contain at least one non-whitespace character and must not exceed 128 UTF-8 bytes.
 */
export type AccessUserPopulationName = string;
