// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessResponseCollection20 {
    errors: CloudflareApi.AccessMessages;
    messages: CloudflareApi.AccessMessages;
    /** Whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.AccessResponseCollection20ResultInfo | undefined;
    result?: CloudflareApi.AccessServiceTokens2[] | undefined;
}
