// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export type AccessEndUserDestinationsItem =
    | CloudflareApi.AccessEndUserDestinationsItem.Public
    | CloudflareApi.AccessEndUserDestinationsItem.Worker
    | CloudflareApi.AccessEndUserDestinationsItem.PreviewWorker
    | CloudflareApi.AccessEndUserDestinationsItem.AllWorkers
    | CloudflareApi.AccessEndUserDestinationsItem.AllPreviewWorkers;

export namespace AccessEndUserDestinationsItem {
    export interface Public extends CloudflareApi.AccessEndUserPublicDestination {
        type: "public";
    }

    export interface Worker extends CloudflareApi.AccessEndUserWorkerDestination {
        type: "worker";
    }

    export interface PreviewWorker extends CloudflareApi.AccessEndUserPreviewWorkerDestination {
        type: "preview_worker";
    }

    export interface AllWorkers extends CloudflareApi.AccessEndUserAllWorkersDestination {
        type: "all_workers";
    }

    export interface AllPreviewWorkers extends CloudflareApi.AccessEndUserAllPreviewWorkersDestination {
        type: "all_preview_workers";
    }
}
