// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AnalyticsSqlSqlQueryRequest {
    params?: CloudflareApi.AnalyticsSqlSqlQueryRequestParams | undefined;
    /** SQL query to execute. A trailing FORMAT selects JSON, JSONEachRow, TabSeparated, or TSV output on any dataset. */
    query: string;
    scope?: CloudflareApi.AnalyticsSqlSqlQueryScope | undefined;
    time_range?: CloudflareApi.AnalyticsSqlSqlQueryTimeRange | undefined;
}
