// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Usage filters. Filters of different kinds are combined with AND, so a record must match every filter present to be returned.
 */
export interface BillableUsageApiV2FilterBy {
    /** Restrict results to rows whose `x_BillableMetricId` matches one of these billable metric ids (e.g. `workers_standard_requests`). Values must be unique. */
    BillableMetricIds?: string[] | undefined;
    /** Restrict results to billable metrics belonging to these product families. Values must be unique UUIDs. */
    ProductFamilyIds?: string[] | undefined;
    /** Restrict results by resource tags. Filters for different keys are combined with AND, while values within one filter are combined with OR. Keys must be unique and are case-sensitive. */
    Tags?: CloudflareApi.BillableUsageApiV2TagFilter[] | undefined;
}
