// This file was auto-generated by Fern from our API Definition.

export interface BrexExtensionEventLogRow {
    action?: string | undefined;
    durationMs?: number | undefined;
    /** Client-generated event ID. Use it to fetch a detection's trace. */
    eventId?: string | undefined;
    eventName?: string | undefined;
    inventoryExtensionId?: string | undefined;
    inventoryExtensionName?: string | undefined;
    inventoryExtensionVersion?: string | undefined;
    matchedDlpProfiles?: string[] | undefined;
    policyId?: string | undefined;
    registrationId?: string | undefined;
    timestamp?: string | undefined;
    url?: string | undefined;
    userEmail?: string | undefined;
}
