// This file was auto-generated by Fern from our API Definition.

export const BrexExtensionEventField = {
    Timestamp: "timestamp",
    DurationMs: "durationMs",
    EventName: "eventName",
    Action: "action",
    UserEmail: "userEmail",
    RegistrationId: "registrationId",
    EventId: "eventId",
    PolicyId: "policyId",
    Url: "url",
    MatchedDlpProfiles: "matchedDlpProfiles",
    InventoryExtensionId: "inventoryExtensionId",
    InventoryExtensionName: "inventoryExtensionName",
    InventoryExtensionVersion: "inventoryExtensionVersion",
} as const;
export type BrexExtensionEventField = (typeof BrexExtensionEventField)[keyof typeof BrexExtensionEventField];
