// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DlpRiskEvent {
    event_details?: Record<string, unknown> | undefined;
    id: string;
    name: string;
    risk_level: CloudflareApi.DlpRiskLevel;
    timestamp: string;
}
