// This file was auto-generated by Fern from our API Definition.

export interface DlpWordListEntry {
    created_at: string;
    enabled: boolean;
    id: string;
    name: string;
    profile_id?: (string | null) | undefined;
    updated_at: string;
    word_list: string[];
}
