// This file was auto-generated by Fern from our API Definition.

/**
 * The BGP mode for a CNI.
 * One of the following:
 * * `dynamic_route_exchange`
 * * `advertise_only`
 */
export const NscBgpMode = {
    DynamicRouteExchange: "dynamic_route_exchange",
    AdvertiseOnly: "advertise_only",
} as const;
export type NscBgpMode = (typeof NscBgpMode)[keyof typeof NscBgpMode];
