// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Contains catalog information.
 */
export interface R2DataCatalogCatalog {
    /** Specifies the associated R2 bucket name. */
    bucket: string;
    /** Shows the credential configuration status. */
    credential_status?: (string | null) | undefined;
    /** Use this to uniquely identify the catalog. */
    id: string;
    /** Configures maintenance for the catalog. */
    maintenance_config?: (CloudflareApi.R2DataCatalogCatalogMaintenanceConfig | null) | undefined;
    /** Specifies the catalog name (generated from account and bucket name). */
    name: string;
    status: CloudflareApi.R2DataCatalogCatalogStatus;
}
