// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Response for device resources
 */
export interface ResourceTaggingTaggedResourceObjectDevice
    extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccountLevelBase {}
