// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Request body schema for deleting tags from account-level resources. Use /zones/{zone_id}/tags for zone-level resources.
 */
export type ResourceTaggingDeleteTagsRequestAccountLevel =
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.AccessApplication
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.AccessGroup
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.Account
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.AccountRuleset
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.AiGateway
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.AlertingPolicy
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.AlertingWebhook
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.CloudflaredTunnel
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.CwsDeployment
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.CwsPolicy
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.CwsPolicySet
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.CwsWorkload
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.D1Database
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.Device
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.DurableObjectNamespace
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.GatewayList
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.GatewayRule
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.Image
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.InfrastructureTarget
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.KvNamespace
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.LoadBalancerMonitor
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.LoadBalancerPool
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.PagesProject
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.Queue
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.R2Bucket
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.ResourceShare
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.StreamLiveInput
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.StreamVideo
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.VectorizeIndex
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.Worker
    | CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevel.WorkerVersion;

export namespace ResourceTaggingDeleteTagsRequestAccountLevel {
    export interface AccessApplication extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "access_application";
    }

    export interface AccessGroup extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "access_group";
    }

    export interface Account extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "account";
    }

    export interface AccountRuleset extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "account_ruleset";
    }

    export interface AiGateway extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "ai_gateway";
    }

    export interface AlertingPolicy extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "alerting_policy";
    }

    export interface AlertingWebhook extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "alerting_webhook";
    }

    export interface CloudflaredTunnel extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "cloudflared_tunnel";
    }

    export interface CwsDeployment extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "cws_deployment";
    }

    export interface CwsPolicy extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "cws_policy";
    }

    export interface CwsPolicySet extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "cws_policy_set";
    }

    export interface CwsWorkload extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "cws_workload";
    }

    export interface D1Database extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "d1_database";
    }

    export interface Device extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "device";
    }

    export interface DurableObjectNamespace extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "durable_object_namespace";
    }

    export interface GatewayList extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "gateway_list";
    }

    export interface GatewayRule extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "gateway_rule";
    }

    export interface Image extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "image";
    }

    export interface InfrastructureTarget extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "infrastructure_target";
    }

    export interface KvNamespace extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "kv_namespace";
    }

    export interface LoadBalancerMonitor extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "load_balancer_monitor";
    }

    export interface LoadBalancerPool extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "load_balancer_pool";
    }

    export interface PagesProject extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "pages_project";
    }

    export interface Queue extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "queue";
    }

    export interface R2Bucket extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "r2_bucket";
    }

    export interface ResourceShare extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "resource_share";
    }

    export interface StreamLiveInput extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "stream_live_input";
    }

    export interface StreamVideo extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "stream_video";
    }

    export interface VectorizeIndex extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "vectorize_index";
    }

    export interface Worker extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelBase {
        resource_type: "worker";
    }

    export interface WorkerVersion extends CloudflareApi.ResourceTaggingDeleteTagsRequestAccountLevelWorkerVersion {
        resource_type: "worker_version";
    }
}
