// This file was auto-generated by Fern from our API Definition.

/** Identifies the type of account-level resource. */
export const ResourceTaggingAccountResourceType = {
    AccessApplication: "access_application",
    AccessGroup: "access_group",
    Account: "account",
    AccountRuleset: "account_ruleset",
    AiGateway: "ai_gateway",
    AlertingPolicy: "alerting_policy",
    AlertingWebhook: "alerting_webhook",
    CloudflaredTunnel: "cloudflared_tunnel",
    CwsDeployment: "cws_deployment",
    CwsPolicy: "cws_policy",
    CwsPolicySet: "cws_policy_set",
    CwsWorkload: "cws_workload",
    D1Database: "d1_database",
    Device: "device",
    DurableObjectNamespace: "durable_object_namespace",
    GatewayList: "gateway_list",
    GatewayRule: "gateway_rule",
    Image: "image",
    InfrastructureTarget: "infrastructure_target",
    KvNamespace: "kv_namespace",
    LoadBalancerMonitor: "load_balancer_monitor",
    LoadBalancerPool: "load_balancer_pool",
    PagesProject: "pages_project",
    Queue: "queue",
    R2Bucket: "r2_bucket",
    ResourceShare: "resource_share",
    StreamLiveInput: "stream_live_input",
    StreamVideo: "stream_video",
    VectorizeIndex: "vectorize_index",
    Worker: "worker",
    WorkerVersion: "worker_version",
} as const;
export type ResourceTaggingAccountResourceType =
    (typeof ResourceTaggingAccountResourceType)[keyof typeof ResourceTaggingAccountResourceType];
