// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Request body schema for setting tags on account-level resources.
 */
export type ResourceTaggingSetTagsRequestAccountLevel =
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.AccessApplication
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.AccessGroup
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.Account
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.AccountRuleset
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.AiGateway
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.AlertingPolicy
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.AlertingWebhook
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.CloudflaredTunnel
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.CwsDeployment
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.CwsPolicy
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.CwsPolicySet
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.CwsWorkload
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.D1Database
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.Device
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.DurableObjectNamespace
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.GatewayList
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.GatewayRule
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.Image
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.InfrastructureTarget
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.KvNamespace
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.LoadBalancerMonitor
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.LoadBalancerPool
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.PagesProject
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.Queue
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.R2Bucket
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.ResourceShare
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.StreamLiveInput
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.StreamVideo
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.VectorizeIndex
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.Worker
    | CloudflareApi.ResourceTaggingSetTagsRequestAccountLevel.WorkerVersion;

export namespace ResourceTaggingSetTagsRequestAccountLevel {
    export interface AccessApplication extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "access_application";
    }

    export interface AccessGroup extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "access_group";
    }

    export interface Account extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "account";
    }

    export interface AccountRuleset extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "account_ruleset";
    }

    export interface AiGateway extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "ai_gateway";
    }

    export interface AlertingPolicy extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "alerting_policy";
    }

    export interface AlertingWebhook extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "alerting_webhook";
    }

    export interface CloudflaredTunnel extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "cloudflared_tunnel";
    }

    export interface CwsDeployment extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "cws_deployment";
    }

    export interface CwsPolicy extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "cws_policy";
    }

    export interface CwsPolicySet extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "cws_policy_set";
    }

    export interface CwsWorkload extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "cws_workload";
    }

    export interface D1Database extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "d1_database";
    }

    export interface Device extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "device";
    }

    export interface DurableObjectNamespace extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "durable_object_namespace";
    }

    export interface GatewayList extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "gateway_list";
    }

    export interface GatewayRule extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "gateway_rule";
    }

    export interface Image extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "image";
    }

    export interface InfrastructureTarget extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "infrastructure_target";
    }

    export interface KvNamespace extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "kv_namespace";
    }

    export interface LoadBalancerMonitor extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "load_balancer_monitor";
    }

    export interface LoadBalancerPool extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "load_balancer_pool";
    }

    export interface PagesProject extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "pages_project";
    }

    export interface Queue extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "queue";
    }

    export interface R2Bucket extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "r2_bucket";
    }

    export interface ResourceShare extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "resource_share";
    }

    export interface StreamLiveInput extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "stream_live_input";
    }

    export interface StreamVideo extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "stream_video";
    }

    export interface VectorizeIndex extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "vectorize_index";
    }

    export interface Worker extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelBase {
        resource_type: "worker";
    }

    export interface WorkerVersion extends CloudflareApi.ResourceTaggingSetTagsRequestAccountLevelWorkerVersion {
        resource_type: "worker_version";
    }
}
