// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export type ResourceTaggingTaggedResourceObject =
    | CloudflareApi.ResourceTaggingTaggedResourceObject.AccessApplication
    | CloudflareApi.ResourceTaggingTaggedResourceObject.AccessApplicationPolicy
    | CloudflareApi.ResourceTaggingTaggedResourceObject.AccessGroup
    | CloudflareApi.ResourceTaggingTaggedResourceObject.Account
    | CloudflareApi.ResourceTaggingTaggedResourceObject.AccountRuleset
    | CloudflareApi.ResourceTaggingTaggedResourceObject.AiGateway
    | CloudflareApi.ResourceTaggingTaggedResourceObject.AlertingPolicy
    | CloudflareApi.ResourceTaggingTaggedResourceObject.AlertingWebhook
    | CloudflareApi.ResourceTaggingTaggedResourceObject.ApiGatewayOperation
    | CloudflareApi.ResourceTaggingTaggedResourceObject.CloudflaredTunnel
    | CloudflareApi.ResourceTaggingTaggedResourceObject.CustomCertificate
    | CloudflareApi.ResourceTaggingTaggedResourceObject.CustomHostname
    | CloudflareApi.ResourceTaggingTaggedResourceObject.CwsDeployment
    | CloudflareApi.ResourceTaggingTaggedResourceObject.CwsPolicy
    | CloudflareApi.ResourceTaggingTaggedResourceObject.CwsPolicySet
    | CloudflareApi.ResourceTaggingTaggedResourceObject.CwsWorkload
    | CloudflareApi.ResourceTaggingTaggedResourceObject.D1Database
    | CloudflareApi.ResourceTaggingTaggedResourceObject.Device
    | CloudflareApi.ResourceTaggingTaggedResourceObject.DnsRecord
    | CloudflareApi.ResourceTaggingTaggedResourceObject.DurableObjectNamespace
    | CloudflareApi.ResourceTaggingTaggedResourceObject.GatewayList
    | CloudflareApi.ResourceTaggingTaggedResourceObject.GatewayRule
    | CloudflareApi.ResourceTaggingTaggedResourceObject.Healthcheck
    | CloudflareApi.ResourceTaggingTaggedResourceObject.Image
    | CloudflareApi.ResourceTaggingTaggedResourceObject.InfrastructureTarget
    | CloudflareApi.ResourceTaggingTaggedResourceObject.KvNamespace
    | CloudflareApi.ResourceTaggingTaggedResourceObject.LoadBalancer
    | CloudflareApi.ResourceTaggingTaggedResourceObject.LoadBalancerMonitor
    | CloudflareApi.ResourceTaggingTaggedResourceObject.LoadBalancerPool
    | CloudflareApi.ResourceTaggingTaggedResourceObject.ManagedClientCertificate
    | CloudflareApi.ResourceTaggingTaggedResourceObject.PagesProject
    | CloudflareApi.ResourceTaggingTaggedResourceObject.Queue
    | CloudflareApi.ResourceTaggingTaggedResourceObject.R2Bucket
    | CloudflareApi.ResourceTaggingTaggedResourceObject.ResourceShare
    | CloudflareApi.ResourceTaggingTaggedResourceObject.StreamLiveInput
    | CloudflareApi.ResourceTaggingTaggedResourceObject.StreamVideo
    | CloudflareApi.ResourceTaggingTaggedResourceObject.VectorizeIndex
    | CloudflareApi.ResourceTaggingTaggedResourceObject.Worker
    | CloudflareApi.ResourceTaggingTaggedResourceObject.WorkerRoute
    | CloudflareApi.ResourceTaggingTaggedResourceObject.WorkerVersion
    | CloudflareApi.ResourceTaggingTaggedResourceObject.Zone
    | CloudflareApi.ResourceTaggingTaggedResourceObject.ZoneRuleset;

export namespace ResourceTaggingTaggedResourceObject {
    export interface AccessApplication extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccessApplication {
        type: "access_application";
    }

    export interface AccessApplicationPolicy
        extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccessApplicationPolicy {
        type: "access_application_policy";
    }

    export interface AccessGroup extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccessGroup {
        type: "access_group";
    }

    export interface Account extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccount {
        type: "account";
    }

    export interface AccountRuleset extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccountRuleset {
        type: "account_ruleset";
    }

    export interface AiGateway extends CloudflareApi.ResourceTaggingTaggedResourceObjectAiGateway {
        type: "ai_gateway";
    }

    export interface AlertingPolicy extends CloudflareApi.ResourceTaggingTaggedResourceObjectAlertingPolicy {
        type: "alerting_policy";
    }

    export interface AlertingWebhook extends CloudflareApi.ResourceTaggingTaggedResourceObjectAlertingWebhook {
        type: "alerting_webhook";
    }

    export interface ApiGatewayOperation extends CloudflareApi.ResourceTaggingTaggedResourceObjectApiGatewayOperation {
        type: "api_gateway_operation";
    }

    export interface CloudflaredTunnel extends CloudflareApi.ResourceTaggingTaggedResourceObjectCloudflaredTunnel {
        type: "cloudflared_tunnel";
    }

    export interface CustomCertificate extends CloudflareApi.ResourceTaggingTaggedResourceObjectCustomCertificate {
        type: "custom_certificate";
    }

    export interface CustomHostname extends CloudflareApi.ResourceTaggingTaggedResourceObjectCustomHostname {
        type: "custom_hostname";
    }

    export interface CwsDeployment extends CloudflareApi.ResourceTaggingTaggedResourceObjectCwsDeployment {
        type: "cws_deployment";
    }

    export interface CwsPolicy extends CloudflareApi.ResourceTaggingTaggedResourceObjectCwsPolicy {
        type: "cws_policy";
    }

    export interface CwsPolicySet extends CloudflareApi.ResourceTaggingTaggedResourceObjectCwsPolicySet {
        type: "cws_policy_set";
    }

    export interface CwsWorkload extends CloudflareApi.ResourceTaggingTaggedResourceObjectCwsWorkload {
        type: "cws_workload";
    }

    export interface D1Database extends CloudflareApi.ResourceTaggingTaggedResourceObjectD1Database {
        type: "d1_database";
    }

    export interface Device extends CloudflareApi.ResourceTaggingTaggedResourceObjectDevice {
        type: "device";
    }

    export interface DnsRecord extends CloudflareApi.ResourceTaggingTaggedResourceObjectDnsRecord {
        type: "dns_record";
    }

    export interface DurableObjectNamespace
        extends CloudflareApi.ResourceTaggingTaggedResourceObjectDurableObjectNamespace {
        type: "durable_object_namespace";
    }

    export interface GatewayList extends CloudflareApi.ResourceTaggingTaggedResourceObjectGatewayList {
        type: "gateway_list";
    }

    export interface GatewayRule extends CloudflareApi.ResourceTaggingTaggedResourceObjectGatewayRule {
        type: "gateway_rule";
    }

    export interface Healthcheck extends CloudflareApi.ResourceTaggingTaggedResourceObjectHealthcheck {
        type: "healthcheck";
    }

    export interface Image extends CloudflareApi.ResourceTaggingTaggedResourceObjectImage {
        type: "image";
    }

    export interface InfrastructureTarget
        extends CloudflareApi.ResourceTaggingTaggedResourceObjectInfrastructureTarget {
        type: "infrastructure_target";
    }

    export interface KvNamespace extends CloudflareApi.ResourceTaggingTaggedResourceObjectKvNamespace {
        type: "kv_namespace";
    }

    export interface LoadBalancer extends CloudflareApi.ResourceTaggingTaggedResourceObjectLoadBalancer {
        type: "load_balancer";
    }

    export interface LoadBalancerMonitor extends CloudflareApi.ResourceTaggingTaggedResourceObjectLoadBalancerMonitor {
        type: "load_balancer_monitor";
    }

    export interface LoadBalancerPool extends CloudflareApi.ResourceTaggingTaggedResourceObjectLoadBalancerPool {
        type: "load_balancer_pool";
    }

    export interface ManagedClientCertificate
        extends CloudflareApi.ResourceTaggingTaggedResourceObjectManagedClientCertificate {
        type: "managed_client_certificate";
    }

    export interface PagesProject extends CloudflareApi.ResourceTaggingTaggedResourceObjectPagesProject {
        type: "pages_project";
    }

    export interface Queue extends CloudflareApi.ResourceTaggingTaggedResourceObjectQueue {
        type: "queue";
    }

    export interface R2Bucket extends CloudflareApi.ResourceTaggingTaggedResourceObjectR2Bucket {
        type: "r2_bucket";
    }

    export interface ResourceShare extends CloudflareApi.ResourceTaggingTaggedResourceObjectResourceShare {
        type: "resource_share";
    }

    export interface StreamLiveInput extends CloudflareApi.ResourceTaggingTaggedResourceObjectStreamLiveInput {
        type: "stream_live_input";
    }

    export interface StreamVideo extends CloudflareApi.ResourceTaggingTaggedResourceObjectStreamVideo {
        type: "stream_video";
    }

    export interface VectorizeIndex extends CloudflareApi.ResourceTaggingTaggedResourceObjectVectorizeIndex {
        type: "vectorize_index";
    }

    export interface Worker extends CloudflareApi.ResourceTaggingTaggedResourceObjectWorker {
        type: "worker";
    }

    export interface WorkerRoute extends CloudflareApi.ResourceTaggingTaggedResourceObjectWorkerRoute {
        type: "worker_route";
    }

    export interface WorkerVersion extends CloudflareApi.ResourceTaggingTaggedResourceObjectWorkerVersion {
        type: "worker_version";
    }

    export interface Zone extends CloudflareApi.ResourceTaggingTaggedResourceObjectZone {
        type: "zone";
    }

    export interface ZoneRuleset extends CloudflareApi.ResourceTaggingTaggedResourceObjectZoneRuleset {
        type: "zone_ruleset";
    }

    export type Request =
        | CloudflareApi.ResourceTaggingTaggedResourceObject.AccessApplication
        | CloudflareApi.ResourceTaggingTaggedResourceObject.AccessApplicationPolicy
        | CloudflareApi.ResourceTaggingTaggedResourceObject.AccessGroup
        | CloudflareApi.ResourceTaggingTaggedResourceObject.Account
        | CloudflareApi.ResourceTaggingTaggedResourceObject.AccountRuleset
        | CloudflareApi.ResourceTaggingTaggedResourceObject.AiGateway
        | CloudflareApi.ResourceTaggingTaggedResourceObject.AlertingPolicy
        | CloudflareApi.ResourceTaggingTaggedResourceObject.AlertingWebhook
        | CloudflareApi.ResourceTaggingTaggedResourceObject.ApiGatewayOperation
        | CloudflareApi.ResourceTaggingTaggedResourceObject.CloudflaredTunnel
        | CloudflareApi.ResourceTaggingTaggedResourceObject.CustomCertificate
        | CloudflareApi.ResourceTaggingTaggedResourceObject.CustomHostname
        | CloudflareApi.ResourceTaggingTaggedResourceObject.CwsDeployment
        | CloudflareApi.ResourceTaggingTaggedResourceObject.CwsPolicy
        | CloudflareApi.ResourceTaggingTaggedResourceObject.CwsPolicySet
        | CloudflareApi.ResourceTaggingTaggedResourceObject.CwsWorkload
        | CloudflareApi.ResourceTaggingTaggedResourceObject.D1Database
        | CloudflareApi.ResourceTaggingTaggedResourceObject.Device
        | CloudflareApi.ResourceTaggingTaggedResourceObject.DnsRecord
        | CloudflareApi.ResourceTaggingTaggedResourceObject.DurableObjectNamespace
        | CloudflareApi.ResourceTaggingTaggedResourceObject.GatewayList
        | CloudflareApi.ResourceTaggingTaggedResourceObject.GatewayRule
        | CloudflareApi.ResourceTaggingTaggedResourceObject.Healthcheck
        | CloudflareApi.ResourceTaggingTaggedResourceObject.Image
        | CloudflareApi.ResourceTaggingTaggedResourceObject.InfrastructureTarget
        | CloudflareApi.ResourceTaggingTaggedResourceObject.KvNamespace
        | CloudflareApi.ResourceTaggingTaggedResourceObject.LoadBalancer
        | CloudflareApi.ResourceTaggingTaggedResourceObject.LoadBalancerMonitor
        | CloudflareApi.ResourceTaggingTaggedResourceObject.LoadBalancerPool
        | CloudflareApi.ResourceTaggingTaggedResourceObject.ManagedClientCertificate
        | CloudflareApi.ResourceTaggingTaggedResourceObject.PagesProject
        | CloudflareApi.ResourceTaggingTaggedResourceObject.Queue
        | CloudflareApi.ResourceTaggingTaggedResourceObject.R2Bucket
        | CloudflareApi.ResourceTaggingTaggedResourceObject.ResourceShare
        | CloudflareApi.ResourceTaggingTaggedResourceObject.StreamLiveInput
        | CloudflareApi.ResourceTaggingTaggedResourceObject.StreamVideo
        | CloudflareApi.ResourceTaggingTaggedResourceObject.VectorizeIndex
        | CloudflareApi.ResourceTaggingTaggedResourceObject.Worker
        | CloudflareApi.ResourceTaggingTaggedResourceObject.WorkerRoute
        | CloudflareApi.ResourceTaggingTaggedResourceObject.WorkerVersion
        | CloudflareApi.ResourceTaggingTaggedResourceObject.Zone
        | CloudflareApi.ResourceTaggingTaggedResourceObject.ZoneRuleset;
}
