// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * The Mesh node connections between your origin and Cloudflare's edge.
 */
export type TunnelWarpConnectorConnections = CloudflareApi.TunnelSchemasWarpConnectorConnection[];
