// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TunnelSchemasWarpConnectorConnection {
    client_id?: CloudflareApi.TunnelClientId | undefined;
    client_version?: CloudflareApi.TunnelVersion | undefined;
    colo_name?: CloudflareApi.TunnelColoName | undefined;
    id?: CloudflareApi.TunnelConnectionId | undefined;
    /** Timestamp of when the connection was established. */
    opened_at?: string | undefined;
    /** The public IP address of the host running the Mesh node connector. */
    origin_ip?: CloudflareApi.TunnelIp | undefined;
}
