// This file was auto-generated by Fern from our API Definition.

/** High-availability mode for the Mesh node. `none` means HA is enabled but no provider is configured yet (newly created nodes default to this). `disabled` means HA is explicitly turned off. `aws` uses AWS ENI move for failover. `local` uses virtual IPs (VIPs) on the local interface. */
export const TunnelMeshHaMode = {
    None: "none",
    Disabled: "disabled",
    Aws: "aws",
    Local: "local",
} as const;
export type TunnelMeshHaMode = (typeof TunnelMeshHaMode)[keyof typeof TunnelMeshHaMode];
