// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * A Mesh node connector that maintains a connection to a Cloudflare data center.
 */
export interface TunnelTunnelWarpConnectorClient {
    arch?: CloudflareApi.TunnelArch | undefined;
    conns?: CloudflareApi.TunnelWarpConnectorConnections | undefined;
    features?: CloudflareApi.TunnelFeatures | undefined;
    ha_status?: CloudflareApi.TunnelHaStatus | undefined;
    id?: CloudflareApi.TunnelClientId | undefined;
    run_at?: CloudflareApi.TunnelRunAt | undefined;
    version?: CloudflareApi.TunnelVersion | undefined;
}
