// This file was auto-generated by Fern from our API Definition.

/** The HA status of a Mesh node connector. */
export const TunnelHaStatus = {
    Offline: "offline",
    Passive: "passive",
    Active: "active",
} as const;
export type TunnelHaStatus = (typeof TunnelHaStatus)[keyof typeof TunnelHaStatus];
