// This file was auto-generated by Fern from our API Definition.

/**
 * A typed tag key containing only Unicode letters or numbers, underscores, periods, or hyphens. The complete UTF-8 encoded tag (the key plus `=` and the value when the value is non-empty) must not exceed 1024 bytes. Cloudflare-reserved prefixes are not accepted.
 */
export type WorkersTypedTagKey = string;
