// This file was auto-generated by Fern from our API Definition.

/**
 * Structured metadata extracted from the event. These fields are indexed and available for filtering and aggregation.
 */
export interface WorkersObservabilityTelemetryEventMetadata {
    /** Cloudflare account identifier. */
    account?: string | undefined;
    /** Cloudflare product that generated this event (e.g. workers, pages). */
    cloudService?: string | undefined;
    coldStart?: number | undefined;
    /** Estimated cost units for this invocation. */
    cost?: number | undefined;
    /** Span duration in milliseconds. */
    duration?: number | undefined;
    /** Span end time as a Unix epoch in milliseconds. */
    endTime?: number | undefined;
    /** Span end time as a Unix epoch in nanoseconds. */
    endTimeNs?: string | undefined;
    /** Error message, present when the log represents an error. */
    error?: string | undefined;
    /** Templatized version of the error message used for grouping similar errors. */
    errorTemplate?: string | undefined;
    /** Content-based fingerprint used to group similar events. */
    fingerprint?: string | undefined;
    /** Unique event ID. Use as the cursor value for offset-based pagination. */
    id: string;
    /** Log level (e.g. log, debug, info, warn, error). */
    level?: string | undefined;
    /** Log message text. */
    message?: string | undefined;
    /** Templatized version of the log message used for grouping similar messages. */
    messageTemplate?: string | undefined;
    /** Metric name when the event represents a metric data point. */
    metricName?: string | undefined;
    /** Origin of the event (e.g. fetch, scheduled, queue). */
    origin?: string | undefined;
    /** Span ID of the parent span in the trace hierarchy. */
    parentSpanId?: string | undefined;
    /** Infrastructure provider identifier. */
    provider?: string | undefined;
    /** Cloudflare Ray ID from the `cf-ray` header of the request that triggered the invocation. */
    rayId?: string | undefined;
    /** Cloudflare data center / region that handled the request. */
    region?: string | undefined;
    /** Cloudflare request ID that ties all logs from a single invocation together. */
    requestId?: string | undefined;
    /** Worker script name that produced this event. */
    service?: string | undefined;
    /** Span ID for this individual unit of work within a trace. */
    spanId?: string | undefined;
    /** Human-readable name for this span. */
    spanName?: string | undefined;
    /** Stack / deployment identifier. */
    stackId?: string | undefined;
    /** Span start time as a Unix epoch in milliseconds. */
    startTime?: number | undefined;
    /** Span start time as a Unix epoch in nanoseconds. */
    startTimeNs?: string | undefined;
    /** HTTP response status code returned by the Worker. */
    statusCode?: number | undefined;
    /** Event time as a Unix epoch in nanoseconds. */
    timestampNs?: string | undefined;
    /** Total duration of the entire trace in milliseconds. */
    traceDuration?: number | undefined;
    /** Distributed trace ID linking spans across services. */
    traceId?: string | undefined;
    /** Logical transaction name for this request. */
    transactionName?: string | undefined;
    /** What triggered the invocation (e.g. GET /users, POST /orders, queue message). */
    trigger?: string | undefined;
    /** Event type classifier (e.g. cf-worker-event, cf-worker-log). */
    type?: string | undefined;
    /** Request URL that triggered the Worker invocation. */
    url?: string | undefined;
}
