// This file was auto-generated by Fern from our API Definition.

/**
 * Tags associated with the Worker, as a key/value object. Each complete UTF-8 encoded tag (the key plus `=` and the value when the value is non-empty) must not exceed 1024 bytes.
 */
export type WorkersTagsKv = Record<string, string>;
