// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface WorkersTagsKvResponse {
    errors: CloudflareApi.WorkersMessages;
    messages: CloudflareApi.WorkersMessages;
    /** Whether the API call was successful. */
    success: true;
    result: CloudflareApi.WorkersTagsKv;
}
