// This file was auto-generated by Fern from our API Definition.

/**
 * The mode of the Workers KV namespace. Specify `instant` when creating a namespace to create a KV Instant namespace. Omit this field when creating a namespace to create a classic namespace. Currently, `instant` is the only supported explicit value.
 */
export type WorkersKvNamespaceMode = "instant";
