// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         "node-id": "tunnel_id"
 *     }
 */
export interface EditNodesRequest {
    /** Cloudflare account ID */
    account_id: string;
    /** UUID of the tunnel. */
    "node-id": string;
    name?: CloudflareApi.TunnelTunnelName;
    tunnel_secret?: CloudflareApi.TunnelTunnelSecret;
}
