// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         "node-id": "tunnel_id",
 *         client_id: "1bedc50d-42b3-473c-b108-ff3d10c0d925"
 *     }
 */
export interface FailoverNodesRequest {
    /** Cloudflare account ID */
    account_id: string;
    /** UUID of the tunnel. */
    "node-id": string;
    client_id: CloudflareApi.TunnelClientIdInput;
}
