// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface ListProposalsRequest {
    /** account id */
    account_id: string;
    /** Page number. */
    page?: number;
    /** Results per page. */
    per_page?: number;
}
