// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         action: "accept",
 *         price_id: 1000000
 *     }
 */
export interface PayPerCrawlPpuOperatorProposalActionRequest {
    /** account id */
    account_id: string;
    action: PayPerCrawlPpuOperatorProposalActionRequest.Action;
    /** Pending pay-per-use price id returned in the operator proposal queue. */
    price_id: number;
}

export namespace PayPerCrawlPpuOperatorProposalActionRequest {
    export const Action = {
        Accept: "accept",
        Reject: "reject",
    } as const;
    export type Action = (typeof Action)[keyof typeof Action];
}
