// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface ListIdentityProvidersResponse {
    result: ListIdentityProvidersResponse.Result.Item[];
    result_info?: ListIdentityProvidersResponse.ResultInfo | undefined;
}

export namespace ListIdentityProvidersResponse {
    export type Result = Result.Item[];

    export namespace Result {
        export type Item =
            | CloudflareApi.AccessAzureAd
            | CloudflareApi.AccessCentrify
            | CloudflareApi.AccessFacebook
            | CloudflareApi.AccessGithub
            | CloudflareApi.AccessGoogle
            | CloudflareApi.AccessGoogleApps
            | CloudflareApi.AccessLinkedin
            | CloudflareApi.AccessOidc
            | CloudflareApi.AccessOkta
            | CloudflareApi.AccessOnelogin
            | CloudflareApi.AccessPingone
            | CloudflareApi.AccessSaml
            | CloudflareApi.AccessYandex
            | CloudflareApi.AccessOnetimepin
            | CloudflareApi.AccessCloudflare
            | CloudflareApi.AccessPasskeys;
    }

    export interface ResultInfo {
        /** Total number of results for the requested service. */
        count?: number | undefined;
        /** Current page within paginated list of results. */
        page?: number | undefined;
        /** Number of results per page of results. */
        per_page?: number | undefined;
        /** Total results available without any search parameters. */
        total_count?: number | undefined;
        /** The number of total pages in the entire result set. */
        total_pages?: number | undefined;
    }
}
