// This file was auto-generated by Fern from our API Definition.

export interface GetScansResponse {
    data: GetScansResponse.Data;
    lists: GetScansResponse.Lists;
    meta: GetScansResponse.Meta;
    page: GetScansResponse.Page;
    scanner: GetScansResponse.Scanner;
    stats: GetScansResponse.Stats;
    task: GetScansResponse.Task;
    verdicts: GetScansResponse.Verdicts;
}

export namespace GetScansResponse {
    export interface Data {
        console: Data.Console.Item[];
        cookies: Data.Cookies.Item[];
        globals: Data.Globals.Item[];
        links: Data.Links.Item[];
        performance: Data.Performance.Item[];
        requests: Data.Requests.Item[];
    }

    export namespace Data {
        export type Console = Console.Item[];

        export namespace Console {
            export interface Item {
                message: Item.Message;
            }

            export namespace Item {
                export interface Message {
                    level: string;
                    source: string;
                    text: string;
                    url: string;
                }
            }
        }

        export type Cookies = Cookies.Item[];

        export namespace Cookies {
            export interface Item {
                domain: string;
                expires: number;
                httpOnly: boolean;
                name: string;
                path: string;
                priority: string;
                sameParty: boolean;
                secure: boolean;
                session: boolean;
                size: number;
                sourcePort: number;
                sourceScheme: string;
                value: string;
            }
        }

        export type Globals = Globals.Item[];

        export namespace Globals {
            export interface Item {
                prop: string;
                type: string;
            }
        }

        export type Links = Links.Item[];

        export namespace Links {
            export interface Item {
                href: string;
                text: string;
            }
        }

        export type Performance = Performance.Item[];

        export namespace Performance {
            export interface Item {
                duration: number;
                entryType: string;
                name: string;
                startTime: number;
            }
        }

        export type Requests = Requests.Item[];

        export namespace Requests {
            export interface Item {
                request: Item.Request;
                requests?: Item.Requests.Item[] | undefined;
                response: Item.Response;
            }

            export namespace Item {
                export interface Request {
                    documentURL: string;
                    frameId?: string | undefined;
                    hasUserGesture: boolean;
                    initiator: Request.Initiator;
                    loaderId?: string | undefined;
                    primaryRequest?: boolean | undefined;
                    redirectHasExtraInfo: boolean;
                    redirectResponse?: Request.RedirectResponse | undefined;
                    request: Request.Request;
                    requestId: string;
                    type: string;
                    wallTime: number;
                }

                export namespace Request {
                    export interface Initiator {
                        host: string;
                        type: string;
                        url: string;
                    }

                    export interface RedirectResponse {
                        charset: string;
                        headers?: Record<string, unknown> | undefined;
                        mimeType: string;
                        protocol: string;
                        remoteIPAddress: string;
                        remotePort: number;
                        securityHeaders: RedirectResponse.SecurityHeaders.Item[];
                        securityState: string;
                        status: number;
                        statusText: string;
                        url: string;
                    }

                    export namespace RedirectResponse {
                        export type SecurityHeaders = SecurityHeaders.Item[];

                        export namespace SecurityHeaders {
                            export interface Item {
                                name: string;
                                value: string;
                            }
                        }
                    }

                    export interface Request {
                        headers?: Record<string, unknown> | undefined;
                        initialPriority: string;
                        isSameSite: boolean;
                        method: string;
                        mixedContentType: string;
                        referrerPolicy: string;
                        url: string;
                    }
                }

                export type Requests = Requests.Item[];

                export namespace Requests {
                    export interface Item {
                        documentURL: string;
                        frameId: string;
                        hasUserGesture: boolean;
                        initiator: Item.Initiator;
                        loaderId: string;
                        redirectHasExtraInfo: boolean;
                        request: Item.Request;
                        requestId: string;
                        type: string;
                        wallTime: number;
                    }

                    export namespace Item {
                        export interface Initiator {
                            type: string;
                        }

                        export interface Request {
                            headers: Request.Headers;
                            initialPriority: string;
                            isSameSite: boolean;
                            method: string;
                            mixedContentType: string;
                            referrerPolicy: string;
                            url: string;
                        }

                        export namespace Request {
                            export interface Headers {
                                name: string;
                            }
                        }
                    }
                }

                export interface Response {
                    asn: Response.Asn;
                    contentAvailable?: boolean | undefined;
                    dataLength: number;
                    encodedDataLength: number;
                    geoip: Response.Geoip;
                    hasExtraInfo: boolean;
                    hash?: string | undefined;
                    requestId: string;
                    response: Response.Response;
                    size: number;
                    type: string;
                }

                export namespace Response {
                    export interface Asn {
                        asn: string;
                        country: string;
                        description: string;
                        ip: string;
                        name: string;
                        org: string;
                    }

                    export interface Geoip {
                        city: string;
                        country: string;
                        country_name: string;
                        geonameId: string;
                        ll: number[];
                        region: string;
                    }

                    export interface Response {
                        charset: string;
                        headers?: Record<string, unknown> | undefined;
                        mimeType: string;
                        protocol: string;
                        remoteIPAddress: string;
                        remotePort: number;
                        securityDetails: Response.SecurityDetails;
                        securityHeaders: Response.SecurityHeaders.Item[];
                        securityState: string;
                        status: number;
                        statusText: string;
                        url: string;
                    }

                    export namespace Response {
                        export interface SecurityDetails {
                            certificateId: number;
                            certificateTransparencyCompliance: string;
                            cipher: string;
                            encryptedClientHello: boolean;
                            issuer: string;
                            keyExchange: string;
                            keyExchangeGroup: string;
                            protocol: string;
                            sanList: string[];
                            serverSignatureAlgorithm: number;
                            subjectName: string;
                            validFrom: number;
                            validTo: number;
                        }

                        export type SecurityHeaders = SecurityHeaders.Item[];

                        export namespace SecurityHeaders {
                            export interface Item {
                                name: string;
                                value: string;
                            }
                        }
                    }
                }
            }
        }
    }

    export interface Lists {
        asns: string[];
        certificates: Lists.Certificates.Item[];
        continents: string[];
        countries: string[];
        domains: string[];
        hashes: string[];
        ips: string[];
        linkDomains: string[];
        servers: string[];
        urls: string[];
    }

    export namespace Lists {
        export type Certificates = Certificates.Item[];

        export namespace Certificates {
            export interface Item {
                issuer: string;
                subjectName: string;
                validFrom: number;
                validTo: number;
            }
        }
    }

    export interface Meta {
        processors: Meta.Processors;
    }

    export namespace Meta {
        export interface Processors {
            agentReadiness?: Processors.AgentReadiness | undefined;
            asn: Processors.Asn;
            dns: Processors.Dns;
            domainCategories: Processors.DomainCategories;
            geoip: Processors.Geoip;
            phishing: Processors.Phishing;
            phishing_v2?: Processors.PhishingV2 | undefined;
            radarRank: Processors.RadarRank;
            robotsTxt?: Processors.RobotsTxt | undefined;
            urlCategories?: Processors.UrlCategories | undefined;
            wappa: Processors.Wappa;
        }

        export namespace Processors {
            export interface AgentReadiness {
                checks: AgentReadiness.Checks;
                commerceSignals?: string[] | undefined;
                isCommerce?: boolean | undefined;
                level: number;
                levelName: string;
                nextLevel?: AgentReadiness.NextLevel | undefined;
            }

            export namespace AgentReadiness {
                export interface Checks {
                    botAccessControl: Checks.BotAccessControl;
                    commerce: Checks.Commerce;
                    contentAccessibility: Checks.ContentAccessibility;
                    discoverability: Checks.Discoverability;
                    discovery: Checks.Discovery;
                }

                export namespace Checks {
                    export interface BotAccessControl {
                        contentSignals: BotAccessControl.ContentSignals;
                        robotsTxtAiRules: BotAccessControl.RobotsTxtAiRules;
                        webBotAuth: BotAccessControl.WebBotAuth;
                    }

                    export namespace BotAccessControl {
                        export interface ContentSignals {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: ContentSignals.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: ContentSignals.MessageRef | undefined;
                            status: string;
                        }

                        export namespace ContentSignals {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface RobotsTxtAiRules {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: RobotsTxtAiRules.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: RobotsTxtAiRules.MessageRef | undefined;
                            status: string;
                        }

                        export namespace RobotsTxtAiRules {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface WebBotAuth {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: WebBotAuth.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: WebBotAuth.MessageRef | undefined;
                            status: string;
                        }

                        export namespace WebBotAuth {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }
                    }

                    export interface Commerce {
                        acp: Commerce.Acp;
                        ap2: Commerce.Ap2;
                        mpp: Commerce.Mpp;
                        ucp: Commerce.Ucp;
                        x402: Commerce.X402;
                    }

                    export namespace Commerce {
                        export interface Acp {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: Acp.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: Acp.MessageRef | undefined;
                            status: string;
                        }

                        export namespace Acp {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface Ap2 {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: Ap2.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: Ap2.MessageRef | undefined;
                            status: string;
                        }

                        export namespace Ap2 {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface Mpp {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: Mpp.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: Mpp.MessageRef | undefined;
                            status: string;
                        }

                        export namespace Mpp {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface Ucp {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: Ucp.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: Ucp.MessageRef | undefined;
                            status: string;
                        }

                        export namespace Ucp {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface X402 {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: X402.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: X402.MessageRef | undefined;
                            status: string;
                        }

                        export namespace X402 {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }
                    }

                    export interface ContentAccessibility {
                        markdownNegotiation: ContentAccessibility.MarkdownNegotiation;
                    }

                    export namespace ContentAccessibility {
                        export interface MarkdownNegotiation {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: MarkdownNegotiation.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: MarkdownNegotiation.MessageRef | undefined;
                            status: string;
                        }

                        export namespace MarkdownNegotiation {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }
                    }

                    export interface Discoverability {
                        dnsAid: Discoverability.DnsAid;
                        linkHeaders: Discoverability.LinkHeaders;
                        robotsTxt: Discoverability.RobotsTxt;
                        sitemap: Discoverability.Sitemap;
                    }

                    export namespace Discoverability {
                        export interface DnsAid {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: DnsAid.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: DnsAid.MessageRef | undefined;
                            status: string;
                        }

                        export namespace DnsAid {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface LinkHeaders {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: LinkHeaders.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: LinkHeaders.MessageRef | undefined;
                            status: string;
                        }

                        export namespace LinkHeaders {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface RobotsTxt {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: RobotsTxt.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: RobotsTxt.MessageRef | undefined;
                            status: string;
                        }

                        export namespace RobotsTxt {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface Sitemap {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: Sitemap.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: Sitemap.MessageRef | undefined;
                            status: string;
                        }

                        export namespace Sitemap {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }
                    }

                    export interface Discovery {
                        a2aAgentCard: Discovery.A2AAgentCard;
                        agentSkills: Discovery.AgentSkills;
                        apiCatalog: Discovery.ApiCatalog;
                        ard: Discovery.Ard;
                        authMd: Discovery.AuthMd;
                        mcpServerCard: Discovery.McpServerCard;
                        oauthDiscovery: Discovery.OauthDiscovery;
                        oauthProtectedResource: Discovery.OauthProtectedResource;
                        webMcp: Discovery.WebMcp;
                    }

                    export namespace Discovery {
                        export interface A2AAgentCard {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: A2AAgentCard.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: A2AAgentCard.MessageRef | undefined;
                            status: string;
                        }

                        export namespace A2AAgentCard {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface AgentSkills {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: AgentSkills.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: AgentSkills.MessageRef | undefined;
                            status: string;
                        }

                        export namespace AgentSkills {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface ApiCatalog {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: ApiCatalog.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: ApiCatalog.MessageRef | undefined;
                            status: string;
                        }

                        export namespace ApiCatalog {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface Ard {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: Ard.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: Ard.MessageRef | undefined;
                            status: string;
                        }

                        export namespace Ard {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface AuthMd {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: AuthMd.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: AuthMd.MessageRef | undefined;
                            status: string;
                        }

                        export namespace AuthMd {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface McpServerCard {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: McpServerCard.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: McpServerCard.MessageRef | undefined;
                            status: string;
                        }

                        export namespace McpServerCard {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface OauthDiscovery {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: OauthDiscovery.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: OauthDiscovery.MessageRef | undefined;
                            status: string;
                        }

                        export namespace OauthDiscovery {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface OauthProtectedResource {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: OauthProtectedResource.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: OauthProtectedResource.MessageRef | undefined;
                            status: string;
                        }

                        export namespace OauthProtectedResource {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }

                        export interface WebMcp {
                            details?: Record<string, unknown> | undefined;
                            durationMs?: number | undefined;
                            evidence?: WebMcp.Evidence.Item[] | undefined;
                            message?: string | undefined;
                            messageRef?: WebMcp.MessageRef | undefined;
                            status: string;
                        }

                        export namespace WebMcp {
                            export type Evidence = Evidence.Item[];

                            export namespace Evidence {
                                export interface Item {
                                    action: string;
                                    finding?: Item.Finding | undefined;
                                    label: string;
                                    request?: Item.Request | undefined;
                                    response?: Item.Response | undefined;
                                }

                                export namespace Item {
                                    export interface Finding {
                                        outcome: string;
                                        summary: string;
                                    }

                                    export interface Request {
                                        headers?: Record<string, unknown> | undefined;
                                        method: string;
                                        url: string;
                                    }

                                    export interface Response {
                                        bodyPreview?: string | undefined;
                                        bodySize?: number | undefined;
                                        headers?: Record<string, unknown> | undefined;
                                        redirectedTo?: string | undefined;
                                        status: number;
                                        statusText: string;
                                    }
                                }
                            }

                            export interface MessageRef {
                                /** Stable, translatable message code. */
                                code: string;
                                params?: Record<string, unknown> | undefined;
                            }
                        }
                    }
                }

                export interface NextLevel {
                    name: string;
                    requirements: NextLevel.Requirements.Item[];
                    target: number;
                }

                export namespace NextLevel {
                    export type Requirements = Requirements.Item[];

                    export namespace Requirements {
                        export interface Item {
                            check: string;
                            description: string;
                            prompt: string;
                            skillUrl: string;
                            specUrls: string[];
                        }
                    }
                }
            }

            export interface Asn {
                data: Asn.Data.Item[];
            }

            export namespace Asn {
                export type Data = Data.Item[];

                export namespace Data {
                    export interface Item {
                        asn: string;
                        country: string;
                        description: string;
                        ip: string;
                        name: string;
                    }
                }
            }

            export interface Dns {
                data: Dns.Data.Item[];
            }

            export namespace Dns {
                export type Data = Data.Item[];

                export namespace Data {
                    export interface Item {
                        address: string;
                        dnssec_valid: boolean;
                        name: string;
                        type: string;
                    }
                }
            }

            export interface DomainCategories {
                data: DomainCategories.Data.Item[];
            }

            export namespace DomainCategories {
                export type Data = Data.Item[];

                export namespace Data {
                    export interface Item {
                        inherited: Record<string, unknown>;
                        isPrimary: boolean;
                        name: string;
                    }
                }
            }

            export interface Geoip {
                data: Geoip.Data.Item[];
            }

            export namespace Geoip {
                export type Data = Data.Item[];

                export namespace Data {
                    export interface Item {
                        geoip: Item.Geoip;
                        ip: string;
                    }

                    export namespace Item {
                        export interface Geoip {
                            city: string;
                            country: string;
                            country_name: string;
                            ll: number[];
                            region: string;
                        }
                    }
                }
            }

            export interface Phishing {
                data: string[];
            }

            export interface PhishingV2 {
                data: string[];
            }

            export interface RadarRank {
                data: RadarRank.Data.Item[];
            }

            export namespace RadarRank {
                export type Data = Data.Item[];

                export namespace Data {
                    export interface Item {
                        bucket: string;
                        hostname: string;
                        rank?: number | undefined;
                    }
                }
            }

            export interface RobotsTxt {
                data: RobotsTxt.Data.Item[];
            }

            export namespace RobotsTxt {
                export type Data = Data.Item[];

                export namespace Data {
                    export interface Item {
                        hash?: string | undefined;
                        rules: Record<string, Item.Rules.Value>;
                        sitemaps: string[];
                    }

                    export namespace Item {
                        export namespace Rules {
                            export interface Value {
                                allow: string[];
                                contentSignal?: Value.ContentSignal | undefined;
                                crawlDelay?: number | undefined;
                                disallow: string[];
                            }

                            export namespace Value {
                                export interface ContentSignal {
                                    "ai-input"?: string | undefined;
                                    "ai-train"?: string | undefined;
                                    search?: string | undefined;
                                }
                            }
                        }
                    }
                }
            }

            export interface UrlCategories {
                data: UrlCategories.Data.Item[];
            }

            export namespace UrlCategories {
                export type Data = Data.Item[];

                export namespace Data {
                    export interface Item {
                        content: Item.Content.Item[];
                        inherited: Item.Inherited;
                        name: string;
                        risks: Item.Risks.Item[];
                    }

                    export namespace Item {
                        export type Content = Content.Item[];

                        export namespace Content {
                            export interface Item {
                                id: number;
                                name: string;
                                super_category_id: number;
                            }
                        }

                        export interface Inherited {
                            content: Inherited.Content.Item[];
                            from: string;
                            risks: Inherited.Risks.Item[];
                        }

                        export namespace Inherited {
                            export type Content = Content.Item[];

                            export namespace Content {
                                export interface Item {
                                    id: number;
                                    name: string;
                                    super_category_id: number;
                                }
                            }

                            export type Risks = Risks.Item[];

                            export namespace Risks {
                                export interface Item {
                                    id: number;
                                    name: string;
                                    super_category_id: number;
                                }
                            }
                        }

                        export type Risks = Risks.Item[];

                        export namespace Risks {
                            export interface Item {
                                id: number;
                                name: string;
                                super_category_id: number;
                            }
                        }
                    }
                }
            }

            export interface Wappa {
                data: Wappa.Data.Item[];
            }

            export namespace Wappa {
                export type Data = Data.Item[];

                export namespace Data {
                    export interface Item {
                        app: string;
                        categories: Item.Categories.Item[];
                        confidence: Item.Confidence.Item[];
                        confidenceTotal: number;
                        icon: string;
                        website: string;
                    }

                    export namespace Item {
                        export type Categories = Categories.Item[];

                        export namespace Categories {
                            export interface Item {
                                name: string;
                                priority: number;
                            }
                        }

                        export type Confidence = Confidence.Item[];

                        export namespace Confidence {
                            export interface Item {
                                confidence: number;
                                name: string;
                                pattern: string;
                                patternType: string;
                            }
                        }
                    }
                }
            }
        }
    }

    export interface Page {
        apexDomain: string;
        asn: string;
        asnname: string;
        city: string;
        country: string;
        domain: string;
        ip: string;
        mimeType: string;
        screenshot?: Page.Screenshot | undefined;
        server: string;
        status: string;
        title: string;
        tlsAgeDays: number;
        tlsIssuer: string;
        tlsValidDays: number;
        tlsValidFrom: string;
        url: string;
    }

    export namespace Page {
        export interface Screenshot {
            dhash: string;
            mm3Hash: number;
            name: string;
            phash: string;
        }
    }

    export interface Scanner {
        colo: string;
        country: string;
    }

    export interface Stats {
        IPv6Percentage: number;
        domainStats: Stats.DomainStats.Item[];
        ipStats: Stats.IpStats.Item[];
        malicious: number;
        protocolStats: Stats.ProtocolStats.Item[];
        resourceStats: Stats.ResourceStats.Item[];
        securePercentage: number;
        secureRequests: number;
        serverStats: Stats.ServerStats.Item[];
        tlsStats: Stats.TlsStats.Item[];
        totalLinks: number;
        uniqASNs: number;
        uniqCountries: number;
    }

    export namespace Stats {
        export type DomainStats = DomainStats.Item[];

        export namespace DomainStats {
            export interface Item {
                count: number;
                countries: string[];
                domain: string;
                encodedSize: number;
                index: number;
                initiators: string[];
                ips: string[];
                redirects: number;
                size: number;
            }
        }

        export type IpStats = IpStats.Item[];

        export namespace IpStats {
            export interface Item {
                asn: Item.Asn;
                count?: number | undefined;
                countries: string[];
                domains: string[];
                encodedSize: number;
                geoip: Item.Geoip;
                index: number;
                ip: string;
                ipv6: boolean;
                redirects: number;
                requests: number;
                size: number;
            }

            export namespace Item {
                export interface Asn {
                    asn: string;
                    country: string;
                    description: string;
                    ip: string;
                    name: string;
                    org: string;
                }

                export interface Geoip {
                    city: string;
                    country: string;
                    country_name: string;
                    ll: number[];
                    region: string;
                }
            }
        }

        export type ProtocolStats = ProtocolStats.Item[];

        export namespace ProtocolStats {
            export interface Item {
                count: number;
                countries: string[];
                encodedSize: number;
                ips: string[];
                protocol: string;
                size: number;
            }
        }

        export type ResourceStats = ResourceStats.Item[];

        export namespace ResourceStats {
            export interface Item {
                compression: number;
                count: number;
                countries: string[];
                encodedSize: number;
                ips: string[];
                percentage: number;
                size: number;
                type: string;
            }
        }

        export type ServerStats = ServerStats.Item[];

        export namespace ServerStats {
            export interface Item {
                count: number;
                countries: string[];
                encodedSize: number;
                ips: string[];
                server: string;
                size: number;
            }
        }

        export type TlsStats = TlsStats.Item[];

        export namespace TlsStats {
            export interface Item {
                count: number;
                countries: string[];
                encodedSize: number;
                ips: string[];
                protocols: Item.Protocols;
                securityState: string;
                size: number;
            }

            export namespace Item {
                export interface Protocols {
                    "TLS 1.3 / AES_128_GCM": number;
                }
            }
        }
    }

    export interface Task {
        apexDomain: string;
        domURL: string;
        domain: string;
        method: string;
        options: Task.Options;
        reportURL: string;
        screenshotURL: string;
        source: string;
        success: boolean;
        time: string;
        url: string;
        uuid: string;
        visibility: string;
    }

    export namespace Task {
        export interface Options {
            /** Custom headers set. */
            customHeaders?: Record<string, unknown> | undefined;
            screenshotsResolutions?: string[] | undefined;
        }
    }

    export interface Verdicts {
        overall: Verdicts.Overall;
    }

    export namespace Verdicts {
        export interface Overall {
            categories: string[];
            hasVerdicts: boolean;
            malicious: boolean;
            tags: string[];
        }
    }
}
