// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "api-version": "2026-10-01.epoch",
 *         account_id: "account_id",
 *         dispatch_namespace: "dispatch_namespace",
 *         script_name: "script_name",
 *         tag: "tag",
 *         value: "production"
 *     }
 */
export interface WorkersTagPatch {
    /** Identifier. */
    account_id: string;
    /** Name of the Workers for Platforms dispatch namespace. */
    dispatch_namespace: string;
    /** Name of the script. */
    script_name: string;
    /** Tag key. Cloudflare-reserved prefixes are not accepted. */
    tag: string;
    /**
     * Requested API compatibility date in `YYYY-MM-DD[.release]` format (UTC). The optional release suffix contains lowercase letters; for example, `2026-10-01.epoch`.
     *
     * Typed Worker tag operations require a date on or after `2026-10-01`.
     */
    "api-version"?: string;
    value: string;
}
