// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         entry_id: "entry_id",
 *         enabled: true,
 *         name: "name",
 *         topic: "topic"
 *     }
 */
export interface DlpCustomPromptTopicUpdate {
    account_id: string;
    entry_id: string;
    description?: string | null;
    enabled: boolean;
    name: string;
    topic: string;
}
