// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         enabled: true,
 *         name: "name",
 *         topic: "topic"
 *     }
 */
export interface DlpNewCustomPromptTopic {
    account_id: string;
    description?: string | null;
    enabled: boolean;
    name: string;
    profile_id?: string;
    topic: string;
}
