// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_tag: "0123456789abcdef0123456789abcdef",
 *         dataset_name: "events.httpRequests"
 *     }
 */
export interface DatasetsSqlRequest {
    /** Account whose available analytics datasets are returned. */
    account_tag: string;
    /** Include column metadata for each returned dataset. */
    include_columns?: boolean;
    /** Include a capped set of custom attribute names and types observed during the preceding seven days. Requires a nonempty dataset_name. */
    include_custom_attributes?: boolean;
    /** Include Workers Analytics Engine datasets, which are discovered from the account's own data. Set to `false` to return only datasets described from the static catalogue, which avoids that lookup. */
    include_wae?: boolean;
    /** Include Log Explorer datasets, which are listed only where the account has them. Set to `false` to return only datasets described from the static catalogue, which avoids that lookup. */
    include_lex?: boolean;
    /**
     * Return only the dataset with this exact name. An empty value is treated as if the parameter had been omitted, and does not filter the catalogue. A name that matches no dataset in this deployment's catalogue is rejected with `422`; a dataset that exists but is not describable here is rejected identically, so the two cases cannot be told apart.
     *
     * A Workers Analytics Engine dataset is named in full, as `events.analyticsEngine.<dataset_name>`; the namespace on its own returns every such dataset the account has. A `dataset_name` the account does not have is rejected with `422` like any other unknown name.
     */
    dataset_name?: string;
}
