// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         title: "My Own Namespace"
 *     }
 */
export interface WorkersKvCreateNamespaceBody {
    /** ID of the Cloudflare account that owns the Workers KV namespaces. */
    account_id: string;
    jurisdiction?: CloudflareApi.WorkersKvJurisdiction;
    /** The mode of the Workers KV namespace. Specify `instant` when creating a namespace to create a KV Instant namespace. Omit this field when creating a namespace to create a classic namespace. Currently, `instant` is the only supported explicit value. */
    mode?: "instant";
    title: CloudflareApi.WorkersKvNamespaceTitle;
}
