// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface SearchThreatEventsRequest {
    /** Account ID. */
    account_id: string;
    forceRefresh?: boolean;
    /** Output format for event data. 'json' returns the default format, 'stix2' returns STIX 2.1 Sighting SROs with linked Indicator SDOs, Observed Data SDOs, and SCOs, 'taxii' returns a TAXII 2.1 Envelope with Content-Type application/taxii+json;version=2.1. */
    format?: CloudflareApi.cloudforceOne.SearchThreatEventsRequestFormat;
    /** Cache strategy. 'from-graph' serves results from the graph-node KV cache when all requested UUIDs are cached; falls back to normal path on partial/zero hit. */
    cache?: CloudflareApi.cloudforceOne.SearchThreatEventsRequestCache;
    /** Cursor for pagination. When provided, filters are embedded in the cursor so you only need to pass cursor and pageSize. */
    cursor?: string;
    /** Dataset UUIDs to query, or one standalone scope value: 'all'/'*' for the legacy all-datasets behavior, 'analytics' for isAnalytics=true datasets, or 'operational' for isAnalytics=false datasets. If not provided, uses the default dataset. */
    datasetId?: string[];
    order?: SearchThreatEventsRequest.Order;
    orderBy?: string;
    page?: number;
    pageSize?: number;
    /** Structured search as a JSON array of {field, op, value} objects. Use the 'in' operator with an array value to bulk-check up to 100 values. Multiple conditions are AND'd together. Max 10 conditions per request. */
    search?: SearchThreatEventsRequest.Search.Item[];
    /** OR branches of structured search filters. Filters within a branch are AND'd, branches are OR'd, and the result is AND'd with `search`: `AND(search) AND OR(AND(branch 1), ...)`. Max 8 branches of 1-10 conditions each. Not supported for analytics datasets, and `indicator` filters are not yet supported inside branches. Cursor pages carry the original branches, so do not resend them with `cursor`. */
    searchBranches?: SearchThreatEventsRequest.SearchBranches.Item[][];
}

export namespace SearchThreatEventsRequest {
    export const Order = {
        Asc: "asc",
        Desc: "desc",
    } as const;
    export type Order = (typeof Order)[keyof typeof Order];
    export type Search = Search.Item[];

    export namespace Search {
        export type Item =
            | {
                  field:
                      | "attacker"
                      | "attackerCountry"
                      | "category"
                      | "createdAt"
                      | "date"
                      | "event"
                      | "indicator"
                      | "indicatorType"
                      | "mitreAttack"
                      | "mitreCapec"
                      | "tags"
                      | "targetCountry"
                      | "targetIndustry"
                      | "tlp"
                      | "uuid";
                  op:
                      | "equals"
                      | "not"
                      | "gt"
                      | "gte"
                      | "lt"
                      | "lte"
                      | "like"
                      | "contains"
                      | "startsWith"
                      | "endsWith"
                      | "find";
                  value: string;
              }
            | {
                  field:
                      | "attacker"
                      | "attackerCountry"
                      | "category"
                      | "createdAt"
                      | "date"
                      | "event"
                      | "indicator"
                      | "indicatorType"
                      | "mitreAttack"
                      | "mitreCapec"
                      | "tags"
                      | "targetCountry"
                      | "targetIndustry"
                      | "tlp"
                      | "uuid";
                  op: "in";
                  value: string[];
              }
            | {
                  field: "killChain";
                  op: "equals" | "not" | "gt" | "gte" | "lt" | "lte";
                  value: number | string;
              }
            | {
                  field: "killChain";
                  op: "in";
                  value: (number | string)[];
              }
            | {
                  field: "hasChildren";
                  op: "equals" | "not" | "gt" | "gte" | "lt" | "lte";
                  value: boolean | "true" | "false" | number | "1" | "0";
              }
            | {
                  field: "hasChildren";
                  op: "in";
                  value: (boolean | "true" | "false" | number | "1" | "0")[];
              };
    }

    export type SearchBranches = SearchBranches.Item[];

    export namespace SearchBranches {
        export type Item =
            | {
                  field:
                      | "attacker"
                      | "attackerCountry"
                      | "category"
                      | "createdAt"
                      | "date"
                      | "event"
                      | "indicator"
                      | "indicatorType"
                      | "mitreAttack"
                      | "mitreCapec"
                      | "tags"
                      | "targetCountry"
                      | "targetIndustry"
                      | "tlp"
                      | "uuid";
                  op:
                      | "equals"
                      | "not"
                      | "gt"
                      | "gte"
                      | "lt"
                      | "lte"
                      | "like"
                      | "contains"
                      | "startsWith"
                      | "endsWith"
                      | "find";
                  value: string;
              }
            | {
                  field:
                      | "attacker"
                      | "attackerCountry"
                      | "category"
                      | "createdAt"
                      | "date"
                      | "event"
                      | "indicator"
                      | "indicatorType"
                      | "mitreAttack"
                      | "mitreCapec"
                      | "tags"
                      | "targetCountry"
                      | "targetIndustry"
                      | "tlp"
                      | "uuid";
                  op: "in";
                  value: string[];
              }
            | {
                  field: "killChain";
                  op: "equals" | "not" | "gt" | "gte" | "lt" | "lte";
                  value: number | string;
              }
            | {
                  field: "killChain";
                  op: "in";
                  value: (number | string)[];
              }
            | {
                  field: "hasChildren";
                  op: "equals" | "not" | "gt" | "gte" | "lt" | "lte";
                  value: boolean | "true" | "false" | number | "1" | "0";
              }
            | {
                  field: "hasChildren";
                  op: "in";
                  value: (boolean | "true" | "false" | number | "1" | "0")[];
              };
    }
}
