// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { ApplicationsClient } from "../resources/applications/client/Client.js";
import { BookmarksClient } from "../resources/bookmarks/client/Client.js";
import { CustomPagesClient } from "../resources/customPages/client/Client.js";
import { InfrastructureClient } from "../resources/infrastructure/client/Client.js";
import { LogsClient } from "../resources/logs/client/Client.js";
import { MfaClient } from "../resources/mfa/client/Client.js";
import { MtlsCertificatesClient } from "../resources/mtlsCertificates/client/Client.js";
import { PoliciesClient } from "../resources/policies/client/Client.js";
import { RuleGroupsClient } from "../resources/ruleGroups/client/Client.js";
import { SamlEncryptionCertificatesClient } from "../resources/samlEncryptionCertificates/client/Client.js";
import { ServiceTokensClient } from "../resources/serviceTokens/client/Client.js";
import { SigningKeysClient } from "../resources/signingKeys/client/Client.js";
import { TagsClient } from "../resources/tags/client/Client.js";
import { TargetsClient } from "../resources/targets/client/Client.js";
import { UserPopulationsClient } from "../resources/userPopulations/client/Client.js";
import { UsersClient } from "../resources/users/client/Client.js";

export declare namespace AccessClient {
    export type Options = BaseClientOptions;
}

export class AccessClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AccessClient.Options>;
    protected _bookmarks: BookmarksClient | undefined;
    protected _customPages: CustomPagesClient | undefined;
    protected _signingKeys: SigningKeysClient | undefined;
    protected _policies: PoliciesClient | undefined;
    protected _samlEncryptionCertificates: SamlEncryptionCertificatesClient | undefined;
    protected _serviceTokens: ServiceTokensClient | undefined;
    protected _tags: TagsClient | undefined;
    protected _userPopulations: UserPopulationsClient | undefined;
    protected _users: UsersClient | undefined;
    protected _targets: TargetsClient | undefined;
    protected _applications: ApplicationsClient | undefined;
    protected _mtlsCertificates: MtlsCertificatesClient | undefined;
    protected _ruleGroups: RuleGroupsClient | undefined;
    protected _infrastructure: InfrastructureClient | undefined;
    protected _logs: LogsClient | undefined;
    protected _mfa: MfaClient | undefined;

    constructor(options: AccessClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get bookmarks(): BookmarksClient {
        return (this._bookmarks ??= new BookmarksClient(this._options));
    }

    public get customPages(): CustomPagesClient {
        return (this._customPages ??= new CustomPagesClient(this._options));
    }

    public get signingKeys(): SigningKeysClient {
        return (this._signingKeys ??= new SigningKeysClient(this._options));
    }

    public get policies(): PoliciesClient {
        return (this._policies ??= new PoliciesClient(this._options));
    }

    public get samlEncryptionCertificates(): SamlEncryptionCertificatesClient {
        return (this._samlEncryptionCertificates ??= new SamlEncryptionCertificatesClient(this._options));
    }

    public get serviceTokens(): ServiceTokensClient {
        return (this._serviceTokens ??= new ServiceTokensClient(this._options));
    }

    public get tags(): TagsClient {
        return (this._tags ??= new TagsClient(this._options));
    }

    public get userPopulations(): UserPopulationsClient {
        return (this._userPopulations ??= new UserPopulationsClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    public get targets(): TargetsClient {
        return (this._targets ??= new TargetsClient(this._options));
    }

    public get applications(): ApplicationsClient {
        return (this._applications ??= new ApplicationsClient(this._options));
    }

    public get mtlsCertificates(): MtlsCertificatesClient {
        return (this._mtlsCertificates ??= new MtlsCertificatesClient(this._options));
    }

    public get ruleGroups(): RuleGroupsClient {
        return (this._ruleGroups ??= new RuleGroupsClient(this._options));
    }

    public get infrastructure(): InfrastructureClient {
        return (this._infrastructure ??= new InfrastructureClient(this._options));
    }

    public get logs(): LogsClient {
        return (this._logs ??= new LogsClient(this._options));
    }

    public get mfa(): MfaClient {
        return (this._mfa ??= new MfaClient(this._options));
    }
}
