// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../index.js";

export type RunSkillsResponse =
    | CloudflareApi.cloudforceOne.threatSignals.articles.RunSkillsResponseZero
    | {
          article_id: string;
          custom_output?: unknown | undefined;
          custom_skill_version: string;
          output_schema: string;
          persisted: true;
          skill_id: string;
      };
