// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../index.js";

export type RunSkillsResponseZero =
    | CloudflareApi.cloudforceOne.threatSignals.articles.RunSkillsResponseZero.DefaultSummarySkill
    | CloudflareApi.cloudforceOne.threatSignals.articles.RunSkillsResponseZero.DefaultTaggingSkill
    | CloudflareApi.cloudforceOne.threatSignals.articles.RunSkillsResponseZero.DefaultIocContextSkill;

export namespace RunSkillsResponseZero {
    export interface DefaultSummarySkill {
        skill_id: "default-summary-skill";
        bullet_points: RunSkillsResponseZeroDefaultSummarySkill.BulletPoints | null;
        persisted: true;
        skill_version: string;
        summary: string;
    }

    export namespace RunSkillsResponseZeroDefaultSummarySkill {
        export interface BulletPoints {
            impact: string;
            what_happened: string;
            who_affected: string;
        }
    }

    export interface DefaultTaggingSkill {
        skill_id: "default-tagging-skill";
        persisted: true;
        tag_skill_version: string;
        /** Final hydrated assignment set; may be empty when no applicable tags are selected. */
        tags: RunSkillsResponseZeroDefaultTaggingSkill.Tags.Item[];
    }

    export namespace RunSkillsResponseZeroDefaultTaggingSkill {
        export type Tags = Tags.Item[];

        export namespace Tags {
            export interface Item {
                applied_by: Item.AppliedBy;
                categoryId: string | null;
                uuid: string;
                value: string;
            }

            export namespace Item {
                export const AppliedBy = {
                    Ai: "ai",
                    Analyst: "analyst",
                    System: "system",
                } as const;
                export type AppliedBy = (typeof AppliedBy)[keyof typeof AppliedBy];
            }
        }
    }

    export interface DefaultIocContextSkill {
        skill_id: "default-ioc-context-skill";
        article_id: string;
        custom_output: RunSkillsResponseZeroDefaultIocContextSkill.CustomOutput;
        custom_skill_version: string;
        output_schema: string;
        persisted: true;
    }

    export namespace RunSkillsResponseZeroDefaultIocContextSkill {
        export interface CustomOutput {
            enrichments: CustomOutput.Enrichments.Item[];
            generated_at: string;
            schema_version: CustomOutput.SchemaVersion;
            source_article_id: string;
        }

        export namespace CustomOutput {
            export type Enrichments = Enrichments.Item[];

            export namespace Enrichments {
                export interface Item {
                    context: Item.Context;
                    infrastructure_assessment: Item.InfrastructureAssessment;
                    role_classification: Item.RoleClassification;
                    skill_metadata: Item.SkillMetadata;
                    target_indicator_id: string;
                    target_indicator_type: string;
                    target_indicator_value: string;
                }

                export namespace Item {
                    export interface Context {
                        context_snippet: string;
                        fetched_at: string;
                        published_at: string;
                        source_article_id: string;
                        source_feed_category?: (string | null) | undefined;
                        source_feed_id: string;
                        source_feed_name: string;
                        source_url: string;
                    }

                    export interface InfrastructureAssessment {
                        affected_scope: string;
                        explanation: string;
                        granularity: InfrastructureAssessment.Granularity;
                        ownership: InfrastructureAssessment.Ownership;
                        parent_domain_legitimate?: (boolean | null) | undefined;
                    }

                    export namespace InfrastructureAssessment {
                        export const Granularity = {
                            ExactIndicator: "exact_indicator",
                            Subdomain: "subdomain",
                            Path: "path",
                            FullDomain: "full_domain",
                            Unknown: "unknown",
                        } as const;
                        export type Granularity = (typeof Granularity)[keyof typeof Granularity];
                        export const Ownership = {
                            ActorOwned: "actor_owned",
                            Compromised: "compromised",
                            AbusedService: "abused_service",
                            Unknown: "unknown",
                        } as const;
                        export type Ownership = (typeof Ownership)[keyof typeof Ownership];
                    }

                    export interface RoleClassification {
                        alternative_roles?: RoleClassification.AlternativeRoles.Item[] | undefined;
                        confidence: RoleClassification.Confidence;
                        evidence_snippet: string;
                        primary_role: RoleClassification.PrimaryRole;
                    }

                    export namespace RoleClassification {
                        export type AlternativeRoles = AlternativeRoles.Item[];

                        export namespace AlternativeRoles {
                            export const Item = {
                                C2: "c2",
                                Dropper: "dropper",
                                PhishingHost: "phishing_host",
                                Loader: "loader",
                                Exfil: "exfil",
                                Recon: "recon",
                            } as const;
                            export type Item = (typeof Item)[keyof typeof Item];
                        }

                        export const Confidence = {
                            High: "high",
                            Medium: "medium",
                            Low: "low",
                        } as const;
                        export type Confidence = (typeof Confidence)[keyof typeof Confidence];
                        export const PrimaryRole = {
                            C2: "c2",
                            Dropper: "dropper",
                            PhishingHost: "phishing_host",
                            Loader: "loader",
                            Exfil: "exfil",
                            Recon: "recon",
                            Unknown: "unknown",
                        } as const;
                        export type PrimaryRole = (typeof PrimaryRole)[keyof typeof PrimaryRole];
                    }

                    export interface SkillMetadata {
                        processing_method: "llm_refined";
                        skill_name: SkillMetadata.SkillName;
                        skill_version: SkillMetadata.SkillVersion;
                    }

                    export namespace SkillMetadata {
                        export const SkillName = {
                            IocContextSkill: "ioc-context-skill",
                        } as const;
                        export type SkillName = (typeof SkillName)[keyof typeof SkillName];
                        export const SkillVersion = {
                            V110: "1.1.0",
                        } as const;
                        export type SkillVersion = (typeof SkillVersion)[keyof typeof SkillVersion];
                    }
                }
            }

            export const SchemaVersion = {
                V110: "1.1.0",
            } as const;
            export type SchemaVersion = (typeof SchemaVersion)[keyof typeof SchemaVersion];
        }
    }
}
