// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_tag: "0123456789abcdef0123456789abcdef",
 *         query: "SELECT edgeResponseStatus FROM events.httpRequests WHERE datetime > '2026-01-01' LIMIT 10"
 *     }
 */
export interface GetAccountsRequest {
    /** Account that authorizes and scopes the request. */
    account_tag: string;
    /** SQL query to execute. A trailing FORMAT selects JSON, JSONEachRow, TabSeparated, or TSV output on any dataset. */
    query: string;
}
