// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_tag: "0123456789abcdef0123456789abcdef",
 *         body: {
 *             query: "SELECT edgeResponseStatus FROM events.httpRequests WHERE edgeResponseStatus = $status LIMIT 10",
 *             scope: {
 *                 accountTag: "0123456789abcdef0123456789abcdef"
 *             },
 *             time_range: {
 *                 end: "2026-01-02T00:00:00Z",
 *                 start: "2026-01-01T00:00:00Z"
 *             }
 *         }
 *     }
 */
export interface PostAccountsRequest {
    /** Account that authorizes and scopes the request. */
    account_tag: string;
    body: CloudflareApi.AnalyticsSqlSqlQueryRequest;
}
