// This file was auto-generated by Fern from our API Definition.

export type ListThreatEventsRequestSearchBranchesItemItem =
    | {
          field:
              | "attacker"
              | "attackerCountry"
              | "category"
              | "createdAt"
              | "date"
              | "event"
              | "indicator"
              | "indicatorType"
              | "mitreAttack"
              | "mitreCapec"
              | "tags"
              | "targetCountry"
              | "targetIndustry"
              | "tlp"
              | "uuid";
          op: "equals" | "not" | "gt" | "gte" | "lt" | "lte" | "like" | "contains" | "startsWith" | "endsWith" | "find";
          value: string;
      }
    | {
          field:
              | "attacker"
              | "attackerCountry"
              | "category"
              | "createdAt"
              | "date"
              | "event"
              | "indicator"
              | "indicatorType"
              | "mitreAttack"
              | "mitreCapec"
              | "tags"
              | "targetCountry"
              | "targetIndustry"
              | "tlp"
              | "uuid";
          op: "in";
          value: string[];
      }
    | {
          field: "killChain";
          op: "equals" | "not" | "gt" | "gte" | "lt" | "lte";
          value: number | string;
      }
    | {
          field: "killChain";
          op: "in";
          value: (number | string)[];
      }
    | {
          field: "hasChildren";
          op: "equals" | "not" | "gt" | "gte" | "lt" | "lte";
          value: boolean | "true" | "false" | number | "1" | "0";
      }
    | {
          field: "hasChildren";
          op: "in";
          value: (boolean | "true" | "false" | number | "1" | "0")[];
      };
