// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id"
 *     }
 */
export interface ListOperatorsPricingRequest {
    /** zone id */
    zone_id: string;
    /** Page number. */
    page?: number;
    /** Results per page. */
    per_page?: number;
}
