// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         operator_id: "operator_id"
 *     }
 */
export interface OptOutOperatorPricePricingRequest {
    /** zone id */
    zone_id: string;
    /** Stable pay-per-use operator identifier. */
    operator_id: string;
}
