// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         operator_id: "operator_id",
 *         body: {
 *             action: "accept_default"
 *         }
 *     }
 */
export interface SetOperatorPricePricingRequest {
    /** zone id */
    zone_id: string;
    /** Stable pay-per-use operator identifier. */
    operator_id: string;
    body: CloudflareApi.PayPerCrawlPpuPublisherPriceActionRequest;
}
